---
settings:
  name: Release notes
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    auto_release_notes_enabled: true
    repositories_features:
    - workload-fsx-ontap
    - 
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Note sulla release di workload Factory
    url: "/index.html"
  - title: Modifiche recenti
    url: "/whats-new.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: Workload Factory
  repo: workload-family
