= 4 agosto 2024
:allow-uri-read: 




== 4 agosto 2024

Direttiva non risolta in <stdin> - include:_include/workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Supporto terraforme

Ora puoi utilizzare Terraform di Codebox per implementare file system e macchine virtuali di storage.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Creare un file system"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Creare una VM di storage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]




=== Consigli su throughput e IOPS nel calcolatore dello storage

Il calcolatore dello storage formula raccomandazioni di configurazione del file system FSX per ONTAP per il throughput e gli IOPS sulla base delle Best practice di AWS, il che ti fornisce una guida ottimale per le tue scelte.

Direttiva non risolta in <stdin> - include:_include/workload-setup-admin.adoc[] :leveloffset: +1



=== Supporto terraforme

Il supporto per Terraform è disponibile per Amazon FSX per l'implementazione del file system NetApp ONTAP e la creazione delle VM di storage. La guida di installazione e amministrazione contiene ora le istruzioni per l'uso di Terraform dal Codebox.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]



== 7 luglio 2024

Direttiva non risolta in <stdin> - include:_include/workload-fsx-ONTAP.adoc[] :leveloffset: +1



=== Release iniziale di workload Factory per Amazon FSX per NetApp ONTAP

Amazon FSX per NetApp ONTAP è ora generalmente disponibile in workload Factory.

Direttiva non risolta in <stdin> - include:_include/workload-setup-admin.adoc[] :leveloffset: +1



=== Release iniziale di workload Factory

BlueXP workload Factory per AWS è una potente piattaforma di gestione del ciclo di vita progettata per aiutarti a ottimizzare i carichi di lavoro utilizzando i file system di Amazon FSX per NetApp ONTAP. I carichi di lavoro che possono essere ottimizzati utilizzando workload Factory e FSX per ONTAP includono database, migrazioni VMware su VMware Cloud su AWS, chatbot ai e altro ancora.
