---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory. 
---
= Modifiche recenti in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory.



== 01 febbraio 2026



=== Workload VMware



==== Analisi well-architected per Amazon Elastic VMware Service

Workload Factory ora fornisce un'analisi automatizzata well-architected per i tuoi ambienti Amazon Elastic VMware Service (EVS). Le scansioni giornaliere identificano disallineamenti di configurazione e offrono raccomandazioni dettagliate per la remediation, aiutandoti a mantenere operatività, sicurezza ed efficienza dei costi ottimali.

Le scansioni vengono eseguite utilizzando le API AWS—non sono necessarie credenziali vSphere o connettività vCenter. I risultati sono disponibili nella nuova scheda *Well-architected status* all'interno dei dettagli dell'ambiente EVS.

Questa release include approfondimenti su:

* *Stato di protezione da arresto/terminazione dell'istanza*: identifica i nodi EVS senza protezione da arresto o terminazione EC2. L'arresto o la terminazione dei nodi EVS dalla console EC2 può causare la non disponibilità o la perdita di dati della macchina virtuale.
* *Allineamento del posizionamento delle partizioni dei nodi del cluster*: rileva disallineamenti di partizionamento che potrebbero causare perdite significative di potenza di elaborazione o tempi di inattività in caso di guasto di una partizione all'interno di una AWS Availability Zone. Ogni insight include livelli di gravità, risultati dettagliati con informazioni sulle risorse interessate e procedure di correzione dettagliate basate sulle AWS best practice.


link:view-evs-well-architected.html["Implementare configurazioni ben architettate"]



=== Installazione e amministrazione



==== Aggiornamenti ben progettati

NetApp Workload Factory include la valutazione ben progettata per i carichi di lavoro Elastic VMware Service (EVS) e aggiunge nuove configurazioni per i carichi di lavoro Storage e Database.

* *Carichi di lavoro VMware* NetApp Workload Factory fornisce best practice e raccomandazioni per l'esecuzione di carichi di lavoro Amazon Elastic VMware Service (EVS) ben architettati.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementare configurazioni EVS ben architettate"^]

* *Carichi di lavoro di archiviazione* Sono state aggiunte diverse nuove configurazioni alla funzionalità ben progettata nel carico di lavoro di archiviazione, in modo da avere una visione più approfondita sulle performance dello storage e sui costi.
+
** Reporting logico della Storage VM
** Ottimizza la dimensione del volume della cache
** Dispositivi a blocchi orfani
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementare configurazioni di file system ben progettate per i carichi di lavoro Storage"^]



* *Carichi di lavoro del database* Workload Factory for Databases include una nuova configurazione dello storage per Oracle per abilitare e configurare Direct NFS (dNFS) per migliorare le prestazioni di I/O e ridurre il carico sull'host e sul sistema storage.
+
** Abilitazione dNFS
** Risoluzione IP coerente dNFS
** file di configurazione dNFS
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare carichi di lavoro di database ben progettati"^]







==== Nuove autorizzazioni per Storage

Sono state aggiunte nuove autorizzazioni al workload Storage per miglioramenti nella gestione dei punti di accesso S3.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



=== Carichi di lavoro dei costruttori



==== Filtraggio della dashboard migliorato con tag personalizzabili

Ora puoi configurare fino a cinque filtri personalizzati sulla dashboard EDA in base ai tuoi tag AWS. Ogni filtro personalizzato include un nome etichetta, una chiave di tag AWS e un tipo di selezione (singola o multipla).

La selezione multipla consente di selezionare più valori contemporaneamente, mentre la selezione singola limita la selezione a un solo valore alla volta. I filtri personalizzati vengono visualizzati nell'ordine in cui li configuri, rendendo facile organizzare i filtri utilizzati più frequentemente.

Se non configuri filtri personalizzati, i filtri predefiniti (file system, tipo di volume e intervallo di tempo) rimangono disponibili così puoi continuare a visualizzare e interagire con i tuoi dashboard.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["Scopri di più sulla configurazione dei filtri personalizzati"^].



==== Visualizzazione dei dettagli del volume per un'analisi granulare delle performance

La dashboard ora offre due modalità di visualizzazione: Total view e Volume view. La Total view mostra metriche aggregate su tutti i volumi, mentre la Volume view mostra le performance individuali dei primi 10 volumi nel tempo.

Nella vista Volume, i suggerimenti interattivi al passaggio del mouse forniscono informazioni dettagliate per ciascun volume, inclusi nome del volume, metriche e valori specifici per il tempo. Quando gli stessi volumi sono presenti in più componenti, la codifica a colori coerente semplifica il monitoraggio di volumi specifici tra diverse metriche.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["Scopri di più sulla visualizzazione dei dettagli del volume"^].



==== Analisi della latenza per il monitoraggio proattivo delle performance

L'analisi della latenza consente di monitorare la latenza di lettura e scrittura dei volumi nei file system FSx for ONTAP. È possibile configurare soglie personalizzabili di avviso e di evento critico per identificare in modo proattivo i colli di bottiglia delle performance prima che influiscano sui carichi di lavoro EDA.

La tabella degli eventi di latenza visualizza tutti gli eventi di avviso e critici, consentendo di monitorare le performance del volume e di identificare i volumi che richiedono ottimizzazione.

Questa funzionalità richiede le credenziali AWS ed è accessibile dal menu Latenza nella dashboard EDA.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["Scopri di più sull'analisi della latenza"^].



== 04 gennaio 2026



=== Amazon FSX per NetApp ONTAP



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* NetApp Autonomous Ransomware Protection (ARP/AI) disabilitato include dispositivi a blocchi: verifica se ARP/AI è disabilitato sui volumi dei dispositivi a blocchi
* Modalità di scrittura della relazione cache: verifica se la modalità di scrittura è ottimale per il carico di lavoro del volume della cache
* Eliminazione dei backup non necessari: verifica se i backup sono obsoleti o non necessari e possono essere eliminati per ridurre i costi


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato dei tuoi file system FSx per ONTAP"]



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



==== Utilizzo del principale utente IAM nei criteri di autorizzazione basati sulle risorse del collegamento Lambda

I collegamenti Lambda utilizzati per la connessione tra l'account Workload Factory e uno o più file system FSx for ONTAP per eseguire operazioni ONTAP avanzate ora utilizzano il principio utente IAM per le autorizzazioni dei criteri basati sulle risorse. Questa modifica garantisce un migliore allineamento con le best practice del settore per l'accesso alle risorse AWS.



==== Schermata di analisi aggiunta per l'analizzatore AI per gli eventi EMS

È stata aggiunta una nuova schermata _Analisi_ al menu Archiviazione. Da questa schermata è possibile utilizzare la funzione AI Analyzer per gli eventi FSx per ONTAP EMS.



==== Miglioramenti dei dispositivi a blocchi in NetApp Workload Factory

Sono stati apportati i seguenti miglioramenti ai dispositivi a blocchi.



===== Creazione di dispositivi a blocchi

NetApp Workload Factory supporta la creazione di dispositivi a blocchi utilizzando il protocollo iSCSI sui file system FSx per ONTAP , in modo da poter supportare al meglio le applicazioni della linea di business (LOB) dalla console Workload Factory.



===== Miglioramenti nella gestione dei dispositivi a blocchi

NetApp Workload Factory include i seguenti miglioramenti per link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["gestione dei dispositivi a blocchi"]. Ora puoi eseguire le seguenti attività dalla console Workload Factory:

* Gestisci l'accesso del cliente
* Archivia i dati del dispositivo a blocchi
* Elimina un dispositivo a blocchi




===== Supporto per ARP/AI su volumi FlexVol contenenti dispositivi a blocchi

Puoi abilitare link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Protezione autonoma dal ransomware NetApp con intelligenza artificiale (ARP/AI)"] sui volumi FlexVol che contengono dispositivi a blocchi. L'abilitazione di ARP/AI rileva gli attacchi ransomware tramite intelligenza artificiale e facilita il recupero dei dati.



=== Workload dei database



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



=== Workload VMware



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



=== Installazione e amministrazione



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



=== Carichi di lavoro dei costruttori



==== NetApp Workload Factory per i costruttori ora NetApp Workload Factory per EDA

Workload Factory for Builders è ora Workload Factory for EDA. Il cambio di nome riflette l'attenzione rivolta ai carichi di lavoro di automazione della progettazione elettronica (EDA).

Workload Factory per EDA ti aiuta a ottimizzare FSx per ONTAP su più file system. È possibile ottimizzare le prestazioni e ridurre i costi operativi automatizzando i parametri di archiviazione, analizzando i vincoli prestazionali e ottenendo informazioni dettagliate sui progetti EDA. Workload Factory per EDA è progettato per integrarsi con i framework Infrastructure as Code (IaC).



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



== 18 dicembre 2025



=== Workload dei database



==== Miglioramenti dell'integrazione di Active Directory

Workload Factory per database include tre nuovi campi Active Directory (AD) quando si distribuisce Microsoft SQL Server utilizzando l'opzione *Creazione avanzata*. Questi miglioramenti consentono di specificare le preferenze di adesione ad Active Directory e di utilizzare un account di servizio gestito.

I nuovi campi AD sono:

* Controller di dominio preferito
* Percorso dell'unità organizzativa preferita
* Gruppo di destinazione Active Directory


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Distribuisci Microsoft SQL Server"]



== 04 dicembre 2025



=== Amazon FSX per NetApp ONTAP



==== Supporto per punti di accesso AWS S3 per FSx per ONTAP

NetApp Workload Factory supporta i punti di accesso AWS S3 per i file system FSx for ONTAP . È possibile creare volumi utilizzando punti di accesso S3, assegnare punti di accesso S3 a un volume esistente e gestire i punti di accesso S3 dalla console Workload Factory. Utilizzando un punto di accesso S3, è possibile accedere ai dati dei file residenti su volumi SMB/CIFS o NFS tramite le API AWS S3. Ciò consente di integrare i dati esistenti con GenAI, ML e analisi dai servizi AWS che supportano i punti di accesso S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Creare un volume utilizzando punti di accesso S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gestire i punti di accesso S3 per un volume"]




== 27 novembre 2025



=== Amazon FSX per NetApp ONTAP



==== Supporto dei dispositivi a blocchi in NetApp Workload Factory

Gestisci i tuoi dispositivi a blocchi in modo più efficace con il nuovo supporto per dispositivi a blocchi introdotto in NetApp Workload Factory. Questa funzionalità consente di visualizzare i dettagli e di aumentare la capacità delle LUN iSCSI, garantendo maggiore flessibilità per le esigenze di archiviazione.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Gestisci i dispositivi a blocchi in Workload Factory"]



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Eliminazione snapshot non necessari: verifica se i volumi contengono snapshot obsoleti e non necessari che possono essere eliminati per ridurre i costi.
* Ribilanciamento dei volumi FlexGroup : verifica se i volumi FlexGroup sono bilanciati uniformemente tra i volumi dei loro membri per garantire prestazioni ottimali.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato dei tuoi file system FSx per ONTAP"]



==== Analizzatore AI per eventi EMS in NetApp Workload Factory

NetApp Workload Factory introduce un analizzatore basato sull'intelligenza artificiale per gli eventi ONTAP Event Management System (EMS). Questa funzionalità ti aiuta a identificare e risolvere rapidamente i problemi fornendo informazioni e consigli basati sull'analisi dei dati degli eventi EMS.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analizza gli eventi EMS in Workload Factory"]



==== Monitorare i trend di costo e utilizzo per i file system FSx per ONTAP

È possibile monitorare i trend di costo e utilizzo dei file system FSx for ONTAP direttamente dalla console NetApp Workload Factory . Questa funzionalità fornisce metriche sui consumi e sui costi di archiviazione, nonché costi dettagliati, aiutandoti a ottimizzare l'allocazione delle risorse e la pianificazione del budget.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Tieni traccia dei costi per i file system FSx per ONTAP in Workload Factory"]



==== Gestire i tag FSx per un file system in NetApp Workload Factory

Gestisci facilmente i tag FSx per un file system direttamente dalla console NetApp Workload Factory . Questa funzionalità consente di aggiungere, modificare o rimuovere tag, consentendo una migliore organizzazione e categorizzazione dei file system FSx per ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Gestisci i tag FSx in Workload Factory"]



==== Regola la capacità della cache per FSx per i file system ONTAP

È possibile aumentare e diminuire la capacità dei volumi di cache dalla console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gestire i volumi di cache in Workload Factory"]



=== Workload dei database



==== Ottimizza i risparmi nel calcolatore dei database per Amazon Elastic Block Store (EBS)

Due nuove funzionalità della calcolatrice migliorano l'analisi del risparmio sui costi quando si eseguono più istanze con storage EBS, in modo da poter risparmiare di più passando a FSx per ONTAP.

* Workload Factory fornisce una soluzione di archiviazione consolidata per diversi host di database su un file system FSx for ONTAP . Questo consolidamento ottimizza i costi di archiviazione riducendo il numero di file system necessari per più host di database, con conseguente maggiore risparmio sui costi.
* Workload Factory analizza l'utilizzo delle prestazioni EBS e suggerisce la configurazione FSx per ONTAP migliore e più conveniente.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Esplora i risparmi per gli host EBS rilevati"]



==== Report Excel disponibile per la dashboard ben progettata

È possibile scaricare un report Excel della dashboard ben progettata. Il report fornisce lo stato di buona progettazione della risorsa del database e raccomandazioni per tutte le configurazioni delle risorse, comprese le sottoconfigurazioni per il sistema operativo e ONTAP.



==== Analizzatore del registro degli errori disponibile per i database Oracle

L'analizzatore del registro degli errori basato sull'intelligenza artificiale Agentic è disponibile per i database Oracle. La funzionalità sfrutta algoritmi avanzati di apprendimento automatico per rilevare e analizzare automaticamente gli errori nei file di registro. Questo strumento mira a semplificare il processo di risoluzione dei problemi fornendo agli sviluppatori informazioni e consigli pratici basati sui modelli identificati nei log.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Scopri di più sull'analizzatore di log degli errori basato sull'intelligenza artificiale Agentic"]



==== Analisi ben progettata per Oracle

L'analisi ben progettata include due nuove configurazioni di dimensionamento dello storage. L'analisi valuta e risolve i problemi di configurazione relativi all'allocazione dello spazio di swap e al margine di spazio del file system per le distribuzioni di database Oracle esistenti.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



=== Workload VMware



==== Calcola il risparmio sui costi della migrazione ad Amazon Elastic VMware Service per regioni specifiche

Ora puoi esplorare il valore delle diverse opzioni di distribuzione per la migrazione al cloud, ottimizzare gli sforzi investiti nella valutazione delle soluzioni e approfondire le soluzioni che hanno il potenziale per offrire valore e risparmi nel cloud.

È inoltre possibile esaminare i risparmi di core vCPU ottenibili utilizzando FSx per ONTAP per una distribuzione EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Scopri i risparmi per Amazon Elastic VMware Service con NetApp Workload Factory"]



=== Installazione e amministrazione



==== Aggiornamento delle autorizzazioni per l'archiviazione

L'analizzatore di eventi FSx for ONTAP EMS utilizza le seguenti autorizzazioni Amazon Bedrock nella policy di autorizzazione _operations and remediation_ per recuperare i dati degli eventi per il carico di lavoro di archiviazione.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]
