---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory. 
---
= Modifiche recenti in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory.



== 04 gennaio 2026



=== Workload dei database



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



=== Workload VMware



==== Chiedimi l'integrazione della home page dell'assistente AI

La home page della console Workload Factory incorpora l'assistente Chiedimi AI, che ti consente di porre domande sul tuo spazio di archiviazione, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti. Puoi interagire con Ask me per comprendere i tuoi carichi di lavoro, risolvere problemi e scoprire di più su Workload Factory, il tutto senza uscire dalla console.



== 18 dicembre 2025



=== Workload dei database



==== Miglioramenti dell'integrazione di Active Directory

Workload Factory per database include tre nuovi campi Active Directory (AD) quando si distribuisce Microsoft SQL Server utilizzando l'opzione *Creazione avanzata*. Questi miglioramenti consentono di specificare le preferenze di adesione ad Active Directory e di utilizzare un account di servizio gestito.

I nuovi campi AD sono:

* Controller di dominio preferito
* Percorso dell'unità organizzativa preferita
* Gruppo di destinazione Active Directory


link:https://docs.netapp.com/us-en/workload-databases/create-database.html["Distribuisci Microsoft SQL Server"]



== 04 dicembre 2025



=== Amazon FSX per NetApp ONTAP



==== Supporto per punti di accesso AWS S3 per FSx per ONTAP

NetApp Workload Factory supporta i punti di accesso AWS S3 per i file system FSx for ONTAP . È possibile creare volumi utilizzando punti di accesso S3, assegnare punti di accesso S3 a un volume esistente e gestire i punti di accesso S3 dalla console Workload Factory. Utilizzando un punto di accesso S3, è possibile accedere ai dati dei file residenti su volumi SMB/CIFS o NFS tramite le API AWS S3. Ciò consente di integrare i dati esistenti con GenAI, ML e analisi dai servizi AWS che supportano i punti di accesso S3.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Creare un volume utilizzando punti di accesso S3"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gestire i punti di accesso S3 per un volume"]




== 27 novembre 2025



=== Amazon FSX per NetApp ONTAP



==== Supporto dei dispositivi a blocchi in NetApp Workload Factory

Gestisci i tuoi dispositivi a blocchi in modo più efficace con il nuovo supporto per dispositivi a blocchi introdotto in NetApp Workload Factory. Questa funzionalità consente di visualizzare i dettagli e di aumentare la capacità delle LUN iSCSI, garantendo maggiore flessibilità per le esigenze di archiviazione.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-devices.html["Gestisci i dispositivi a blocchi in Workload Factory"]



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Eliminazione snapshot non necessari: verifica se i volumi contengono snapshot obsoleti e non necessari che possono essere eliminati per ridurre i costi.
* Ribilanciamento dei volumi FlexGroup : verifica se i volumi FlexGroup sono bilanciati uniformemente tra i volumi dei loro membri per garantire prestazioni ottimali.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato dei tuoi file system FSx per ONTAP"]



==== Analizzatore AI per eventi EMS in NetApp Workload Factory

NetApp Workload Factory introduce un analizzatore basato sull'intelligenza artificiale per gli eventi ONTAP Event Management System (EMS). Questa funzionalità ti aiuta a identificare e risolvere rapidamente i problemi fornendo informazioni e consigli basati sull'analisi dei dati degli eventi EMS.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/analyze-events.html["Analizza gli eventi EMS in Workload Factory"]



==== Monitorare i trend di costo e utilizzo per i file system FSx per ONTAP

È possibile monitorare i trend di costo e utilizzo dei file system FSx for ONTAP direttamente dalla console NetApp Workload Factory . Questa funzionalità fornisce metriche sui consumi e sui costi di archiviazione, nonché costi dettagliati, aiutandoti a ottimizzare l'allocazione delle risorse e la pianificazione del budget.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html["Tieni traccia dei costi per i file system FSx per ONTAP in Workload Factory"]



==== Gestire i tag FSx per un file system in NetApp Workload Factory

Gestisci facilmente i tag FSx per un file system direttamente dalla console NetApp Workload Factory . Questa funzionalità consente di aggiungere, modificare o rimuovere tag, consentendo una migliore organizzazione e categorizzazione dei file system FSx per ONTAP .

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-fsx-tags.html["Gestisci i tag FSx in Workload Factory"]



==== Regola la capacità della cache per FSx per i file system ONTAP

È possibile aumentare e diminuire la capacità dei volumi di cache dalla console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gestire i volumi di cache in Workload Factory"]



=== Workload dei database



==== Ottimizza i risparmi nel calcolatore dei database per Amazon Elastic Block Store (EBS)

Due nuove funzionalità della calcolatrice migliorano l'analisi del risparmio sui costi quando si eseguono più istanze con storage EBS, in modo da poter risparmiare di più passando a FSx per ONTAP.

* Workload Factory fornisce una soluzione di archiviazione consolidata per diversi host di database su un file system FSx for ONTAP . Questo consolidamento ottimizza i costi di archiviazione riducendo il numero di file system necessari per più host di database, con conseguente maggiore risparmio sui costi.
* Workload Factory analizza l'utilizzo delle prestazioni EBS e suggerisce la configurazione FSx per ONTAP migliore e più conveniente.


link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Esplora i risparmi per gli host EBS rilevati"]



==== Report Excel disponibile per la dashboard ben progettata

È possibile scaricare un report Excel della dashboard ben progettata. Il report fornisce lo stato di buona progettazione della risorsa del database e raccomandazioni per tutte le configurazioni delle risorse, comprese le sottoconfigurazioni per il sistema operativo e ONTAP.



==== Analizzatore del registro degli errori disponibile per i database Oracle

L'analizzatore del registro degli errori basato sull'intelligenza artificiale Agentic è disponibile per i database Oracle. La funzionalità sfrutta algoritmi avanzati di apprendimento automatico per rilevare e analizzare automaticamente gli errori nei file di registro. Questo strumento mira a semplificare il processo di risoluzione dei problemi fornendo agli sviluppatori informazioni e consigli pratici basati sui modelli identificati nei log.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Scopri di più sull'analizzatore di log degli errori basato sull'intelligenza artificiale Agentic"]



==== Analisi ben progettata per Oracle

L'analisi ben progettata include due nuove configurazioni di dimensionamento dello storage. L'analisi valuta e risolve i problemi di configurazione relativi all'allocazione dello spazio di swap e al margine di spazio del file system per le distribuzioni di database Oracle esistenti.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



=== Workload VMware



==== Calcola il risparmio sui costi della migrazione ad Amazon Elastic VMware Service per regioni specifiche

Ora puoi esplorare il valore delle diverse opzioni di distribuzione per la migrazione al cloud, ottimizzare gli sforzi investiti nella valutazione delle soluzioni e approfondire le soluzioni che hanno il potenziale per offrire valore e risparmi nel cloud.

È inoltre possibile esaminare i risparmi di core vCPU ottenibili utilizzando FSx per ONTAP per una distribuzione EVS.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Scopri i risparmi per Amazon Elastic VMware Service con NetApp Workload Factory"]



=== Installazione e amministrazione



==== Aggiornamento delle autorizzazioni per l'archiviazione

L'analizzatore di eventi FSx for ONTAP EMS utilizza le seguenti autorizzazioni Amazon Bedrock nella policy di autorizzazione _operations and remediation_ per recuperare i dati degli eventi per il carico di lavoro di archiviazione.

* `bedrock:ListInferenceProfiles`
* `bedrock:GetInferenceProfile`
* `bedrock:InvokeModelWithResponseStream`
* `bedrock:InvokeModel`


link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



== 02 novembre 2025



=== Amazon FSX per NetApp ONTAP



==== Gestione del volume della cache

È possibile eseguire le seguenti operazioni di gestione del volume della cache dalla console di Workload Factory:

* Modifica il nome della cache
* Aumentare la capacità di un volume di cache
* Modifica il percorso di montaggio o la politica di esportazione per un volume di cache
* Modificare il metodo o la modalità di memorizzazione nella cache per un volume di cache
* Precompilare un volume di cache
* Elimina un volume di cache


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gestisci i volumi della cache"]



==== Gestione automatica degli inode disponibile

È possibile abilitare la gestione automatica degli inode senza dover abilitare la gestione automatica della capacità.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Abilita la gestione automatica degli inode"]



==== Impostazione di avviso di soglia per l'utilizzo di capacità e inode

Sono disponibili avvisi di soglia sia per la capacità che per l'utilizzo degli inode. È possibile impostare queste soglie quando si abilita la gestione automatica della capacità o degli inode. Per utilizzare questa impostazione, dovrai configurare le notifiche utilizzandolink:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Servizio di notifica NetApp Workload Factory"^] .



==== Riduzione delle dimensioni del volume disponibile

È possibile ridurre le dimensioni dei volumi NFS e SMB/CIFS in NetApp Workload Factory. Questa funzionalità consente una migliore gestione delle risorse di archiviazione, consentendo di ridurre le dimensioni dei volumi che non sono più necessari alla loro capacità attuale.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Diminuire la capacità di un volume"]



==== FSx migliorato per lo stato delle risorse ONTAP

Workload Factory ha migliorato lo stato della risorsa "non configurata" per includere una spiegazione del problema effettivo della risorsa.



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Utilizzo del volume quasi completo: controlla se uno qualsiasi dei volumi sta utilizzando l'80% o più della propria capacità di file. Ciò consente di identificare i volumi che potrebbero richiedere capacità aggiuntiva.
* Accesso non autorizzato ai volumi: verifica se un volume iSCSI è accessibile tramite un percorso di montaggio NFS o SMB/CIFS e consente di rimuovere l'accesso non autorizzato al volume per evitare rischi per la sicurezza.




==== Modifiche alle autorizzazioni per Workload Factory per Storage

Workload Factory fornisce maggiore chiarezza sulle autorizzazioni richieste per azioni specifiche e granularità per selezionare solo le autorizzazioni necessarie. Quando aggiungi le credenziali, avrai tre opzioni di autorizzazioni tra cui scegliere, anziché il precedente modello di autorizzazioni che era _sola lettura_ e _lettura/scrittura_. Il nuovo modello di autorizzazioni suddivide le policy di autorizzazione come segue:

* _Visualizzazione, pianificazione e analisi_: visualizza i file system FSx per ONTAP , scopri di più sullo stato del sistema, ottieni un'analisi ben progettata per i tuoi sistemi ed esplora i risparmi.
* _Operazioni e risoluzione_: esegui attività operative come la regolazione della capacità del file system e la risoluzione dei problemi relativi alle configurazioni del file system.
* _Creazione ed eliminazione del file system_: crea ed elimina FSx per i file system ONTAP e le VM di archiviazione.


Quando si aggiungono le credenziali, è possibile selezionare una o più di queste policy di autorizzazione in base al livello di accesso che si desidera fornire a Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Riferimento alle autorizzazioni di Workload Factory"]



==== Supporto per FSx per ONTAP Cyber ​​Vault

È possibile creare un cyber vault utilizzando FSx for ONTAP come origine o destinazione nell'architettura del cyber vault. I caveau informatici forniscono un ambiente sicuro e isolato per l'archiviazione di dati critici, proteggendoli da ransomware e altre minacce informatiche.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Configurare un cyber vault con FSx per ONTAP"]



=== Workload dei database



==== Miglioramenti della dashboard

La nuova dashboard è semplificata e meglio organizzata per fornire una panoramica più chiara delle risorse del database e delle funzionalità chiave di Workload Factory in un'unica schermata; una scheda evidenzia le risorse del database, una scheda fornisce informazioni sul punteggio e sull'analisi ben strutturati, una scheda visualizza l'analisi degli errori, due schede visualizzano i costi mensili e i potenziali risparmi e una scheda visualizza informazioni sulle sandbox.



==== Analisi ben progettata per Oracle

L'analisi ben progettata include le seguenti valutazioni e correzioni per le configurazioni Oracle:

* Sistema operativo di configurazione dell'archiviazione mediante protocollo NFS: valuta e risolve i problemi di configurazione con la configurazione NFS per le distribuzioni di database Oracle esistenti.
* Sistema operativo di configurazione dell'archiviazione mediante protocollo iSCSI: valuta e risolve i problemi di configurazione con la configurazione iSCSI per le distribuzioni di database Oracle esistenti.
* Sistema operativo di configurazione dell'archiviazione mediante Automatic Storage Management (ASM): valuta i problemi di configurazione con la configurazione ASM per le distribuzioni di database Oracle esistenti.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



==== Modifiche alle autorizzazioni per Workload Factory per database

Workload Factory for Databases ha aggiornato i criteri di autorizzazione per fornire maggiore chiarezza su ciò che richiede per azioni specifiche e granularità per selezionare solo le autorizzazioni necessarie. Quando aggiungi le credenziali, avrai tre opzioni di autorizzazioni tra cui scegliere, anziché il precedente modello di autorizzazioni che era _sola lettura_ e _lettura/scrittura_. Il nuovo modello di autorizzazioni suddivide le policy di autorizzazione come segue:

* _Visualizzazione, pianificazione e analisi_: visualizza l'inventario delle risorse del database, scopri lo stato di salute delle tue risorse, esamina l'analisi ben progettata delle configurazioni del tuo database, ottieni l'analisi del registro degli errori ed esplora i risparmi
* _Operazioni e risoluzione_: esegui attività operative per le risorse del tuo database e risolvi problemi per le configurazioni del database e l'archiviazione del file system FSx for ONTAP sottostante
* _Creazione host database_: distribuire host database e FSx sottostante per l'archiviazione del file system ONTAP secondo le best practice


Quando si aggiungono le credenziali, è possibile selezionare una o più di queste policy di autorizzazione in base al livello di accesso che si desidera fornire a Workload Factory for Databases.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Riferimento alle autorizzazioni di Workload Factory"^]



==== Aggiunta schermata dashboard ben progettata

Una nuova schermata del dashboard _Well-architected_ è stata aggiunta al menu Database. Da questa schermata è possibile ottenere una visualizzazione aggregata dello stato di configurazione dell'intero database.



==== Protezione delle modifiche per le distribuzioni di database in NetApp Backup and Recovery

Dalla console Workload Factory, puoi scegliere di modificare la protezione per una risorsa protetta e poi verrai reindirizzato a Backup e ripristino nella NetApp Console , dove potrai modificare la policy o la pianificazione della protezione.

link:https://docs.netapp.com/us-en/workload-databases/protect-sql-server.html["Protezione delle modifiche per le distribuzioni di database"]



==== Filtraggio degli errori tramite tag disponibile per la funzionalità di analisi degli errori

È possibile filtrare e visualizzare i log degli errori di Microsoft SQL Server in base a tag orientati all'infrastruttura quando si utilizza la funzionalità di analisi degli errori in Workload Factory. Questo miglioramento ti aiuta a individuare, risolvere e risolvere rapidamente i problemi.

link:https://docs.netapp.com/us-en/workload-databases/analyze-error-logs.html["Analizza i registri degli errori con il filtraggio dei tag"^]



=== Workload VMware



==== Introduzione delle preferenze di Amazon Elastic VMware Service nella procedura guidata di distribuzione del file system FSx for ONTAP

Quando si distribuisce un file system FSx for ONTAP da utilizzare come datastore NFS esterni per Amazon Elastic VMware Service, è ora possibile selezionare l'ambiente EVS a cui verranno connessi i datastore. In questo modo vengono compilati automaticamente diversi campi nella procedura guidata di distribuzione per semplificare il processo di distribuzione.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Distribuire il file system FSx per ONTAP consigliato"]



==== Modifiche alle autorizzazioni per i carichi di lavoro VMware

I carichi di lavoro VMware forniscono maggiore chiarezza sulle autorizzazioni richieste per azioni specifiche e granularità per selezionare solo le autorizzazioni necessarie. Quando aggiungi le credenziali, avrai due opzioni di autorizzazioni tra cui scegliere invece del precedente modello di autorizzazioni che era _sola lettura_ e _lettura/scrittura_. Il nuovo modello di autorizzazioni suddivide le policy di autorizzazione come segue:

* _Visualizzazione, pianificazione e analisi_: visualizza l'inventario degli ambienti di virtualizzazione EVS, ottieni un'analisi ben progettata per i tuoi sistemi ed esplora i risparmi.
* _Distribuzione e connettività del datastore_: distribuisci i layout VM consigliati sui cluster Amazon EVS, Amazon EC2 o VMware Cloud su AWS vSphere e utilizza i file system Amazon FSx for NetApp ONTAP personalizzati come datastore esterni.


Quando si aggiungono le credenziali, è possibile selezionare una o più di queste policy di autorizzazione in base al livello di accesso che si desidera fornire ai carichi di lavoro VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Riferimento alle autorizzazioni di Workload Factory"^]



==== Miglioramenti del consulente per la migrazione di Amazon EC2

Questa versione di NetApp Workload Factory per VMware presenta diversi miglioramenti all'esperienza di consulenza sulla migrazione:

* *Salva o scarica un piano di migrazione*: ora puoi salvare o scaricare un piano di migrazione come file PDF o CSV. Quando salvi un piano di migrazione, il piano viene salvato con il tuo account Workload Factory.




=== Installazione e amministrazione



==== Aggiornamento dei permessi

In questa versione abbiamo apportato aggiornamenti significativi ai criteri di autorizzazione per i carichi di lavoro di archiviazione, database e VMware per migliorare la sicurezza e il controllo degli utenti. Puoi personalizzare le impostazioni delle autorizzazioni in modo più dettagliato, aggiungendo o eliminando autorizzazioni come preferisci.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Riferimento alle autorizzazioni per Workload Factory"]



==== Nuova notifica per Storage

Il servizio di notifica NetApp Workload Factory include la notifica per la gestione automatica degli inode per Storage.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Notifiche per NetApp Workload Factory"]



==== Avvisi di soglia per la gestione automatica della capacità e degli inode

È possibile impostare la gestione automatica della capacità e degli inode per l'archiviazione con una soglia di avviso che attiva una notifica dal servizio di notifica Workload Factory. Per utilizzare questa funzionalità, è necessario prima abilitare il servizio di notifica Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche per NetApp Workload Factory"]
