---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Scopri le modifiche più recenti ai carichi di lavoro che fanno parte della fabbrica di carichi di lavoro BlueXP . 
---
= Recenti cambiamenti nella fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti ai carichi di lavoro che fanno parte della fabbrica di carichi di lavoro BlueXP .



== 2025-06-30



=== Workload dei database



==== Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP

Il servizio di notifica di BlueXP Workload Factory consente a Workload Factory di inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche di fabbrica del carico di lavoro BlueXP"^]

Workload Factory fornisce le seguenti notifiche per i database:

* Rapporto ben progettato
* Distribuzione host
* Protezione




==== Miglioramento dell'onboarding per la registrazione delle istanze

Workload Factory per Database ha migliorato il processo di onboarding per la registrazione delle istanze in esecuzione su Amazon FSx per lo storage NetApp ONTAP. Ora è possibile selezionare le istanze in blocco per la registrazione. Una volta registrata un'istanza, è possibile creare e gestire le risorse host del database all'interno della console di Workload Factory.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestione delle istanze"]



==== Analisi e correzione per l'impostazione del timeout di Microsoft Multipath I/O

Lo stato "Well Architectured" per le istanze host del database ora include l'analisi e la correzione per l'impostazione di timeout di Microsoft Multipath I/O (MPIO). L'impostazione del timeout MPIO a 60 secondi garantisce la connettività e la stabilità dello storage FSx for ONTAP durante i failover. Se l'impostazione MPIO non è impostata correttamente, Workload Factory fornirà una correzione per impostare il valore di timeout MPIO a 60 secondi.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate nella fabbrica dei carichi di lavoro"]



==== Miglioramenti alla grafica nell'inventario host

Dalla schermata dell'inventario host, diversi grafici sull'utilizzo delle risorse, come throughput e IOPS, ora mostrano i dati degli ultimi 7 giorni, consentendo di monitorare le prestazioni dei nodi SQL dalla console di Workload Factory in modo più efficiente. I parametri delle prestazioni raccolti dai nodi SQL verranno salvati in Amazon CloudWatch e potranno essere utilizzati per Logs Insights o per l'integrazione con altri servizi di analisi nel tuo ambiente.

Nelle schede Istanze e Database all'interno dell'inventario host, abbiamo migliorato la descrizione e la visualizzazione per la protezione host.



==== Supporto per l'autenticazione di Windows nella fabbrica dei carichi di lavoro

Ora Workload Factory supporta l'autenticazione di SQL Server utilizzando utenti autenticati Windows per registrare istanze host e trarre vantaggio dalle funzionalità di gestione host.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registra le istanze host nella fabbrica dei carichi di lavoro per i database"]



== 2025-06-29



=== Amazon FSX per NetApp ONTAP



==== Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP

Il servizio di notifica di BlueXP Workload Factory consente a Workload Factory di inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche di fabbrica del carico di lavoro BlueXP"^]



==== Miglioramenti della dashboard di archiviazione

La dashboard di Storage nella console di Workload Factory include nuove schede per le opportunità di risparmio. La scheda nella parte superiore della dashboard mostra il numero di opportunità di risparmio per gli ambienti di storage in esecuzione su Amazon Elastic Block Store (EBS), Amazon FSx for Windows File Server e Amazon Elastic File Systems (EFS). Nella parte inferiore della dashboard, tre nuove schede mostrano le opportunità di risparmio per servizio di storage Amazon: EBS, FSx for Windows File Server ed EFS. Da tutte le schede è possibile esplorare le opportunità di risparmio in modo più dettagliato.

Dalla scheda di copertura della protezione di FSx for ONTAP e dalla scheda di stato delle relazioni di replicazione, è possibile verificare la presenza di volumi parzialmente protetti nei file system di FSx for ONTAP e individuare eventuali problemi relativi alle relazioni di replicazione. In entrambi i casi, è possibile intervenire per risolvere i problemi.



==== Miglioramenti della scheda Volume

La scheda Volumi nella console di Workload Factory è stata migliorata per offrire una panoramica più completa dei file system FSx for ONTAP. I miglioramenti includono nuove schede per la capacità SSD, il pool di capacità e la protezione autonoma da ransomware NetApp con intelligenza artificiale (ARP/AI). Queste schede riepilogano l'utilizzo della capacità e la protezione ARP/AI per tutti i volumi del file system.



==== Supporto di Amazon FSX per i file system NetApp ONTAP di seconda generazione

Workload Factory ora supporta i file system Amazon FSx for NetApp ONTAP di seconda generazione. È possibile creare, gestire e monitorare i file system di seconda generazione nella console di Workload Factory. Sono supportate tutte le nuove regioni commerciali.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Creare un file system di seconda generazione nella fabbrica dei carichi di lavoro"]



==== Supporto del volume FlexVol per il ribilanciamento della capacità del volume

I volumi FlexVol sono individuabili nella console Workload Factory. È possibile verificare il bilanciamento dei volumi FlexVol e ribilanciarli per ridistribuire la capacità quando si verificano squilibri nel tempo dovuti all'aggiunta di nuovi file o alla crescita del numero di file.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Riequilibrare la capacità di un volume FlexVol"]



==== Aggiornamento della terminologia

Il termine "Autonomous Ransomware Protection" (ARP) è stato aggiornato in "NetApp Autonomous Ransomware Protection with AI" (ARP/AI) nella console Workload Factory.



==== ARP/AI abilitato per impostazione predefinita per i nuovi volumi

Quando si crea un nuovo volume nella console di Workload Factory, NetApp Autonomous Ransomware Protection con IA (ARP/AI) è abilitato per impostazione predefinita se il file system dispone di una policy ARP/AI. Ciò significa che il volume viene automaticamente protetto dagli attacchi ransomware utilizzando funzionalità di rilevamento e risposta basate sull'IA.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crea un volume nella fabbrica del carico di lavoro"]



==== Supporto di replicazione per file immutabili

Workload Factory supporta la replica di volumi immutabili da un sistema FSx for ONTAP a un altro file system FSx for ONTAP per proteggere i dati critici da eliminazioni accidentali o attacchi dannosi come il ransomware. Il volume di destinazione e il relativo file system host saranno immutabili, o bloccati, e tutti i dati nel file system di destinazione non potranno essere modificati o rimossi fino al termine del periodo di conservazione.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Scopri come creare una relazione di replicazione"]



==== Miglioramenti nella creazione di link

Sono stati apportati i seguenti miglioramenti al processo di creazione dei collegamenti nella console Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connettersi a un file system FSX per ONTAP con un collegamento Lambda"]



===== Gestire il ruolo e le autorizzazioni di esecuzione IAM durante la creazione del collegamento

Ora puoi gestire il ruolo di esecuzione IAM e la relativa policy di autorizzazione quando crei un collegamento nella console della Workload Factory. Un collegamento stabilisce la connettività tra il tuo account della Workload Factory e uno o più file system FSx for ONTAP. Sono disponibili due opzioni per l'assegnazione del ruolo di esecuzione IAM e delle autorizzazioni di collegamento: automaticamente o tramite l'utente. Gestire il ruolo di esecuzione e la relativa policy di autorizzazione nella Workload Factory significa che non è più necessario utilizzare codice di terze parti.



===== Supporto Terraform per la creazione di collegamenti

Ora è possibile utilizzare Terraform dal Codebox per creare un collegamento da associare a un file system FSx for ONTAP. Questa funzionalità è riservata agli utenti che creano collegamenti manualmente.



=== Workload VMware



==== Introduzione del supporto di Migration Advisor per Amazon Elastic VMWare Service

BlueXP Workload Factory per VMware ora supporta Amazon Elastic VMware Service. Puoi migrare rapidamente i tuoi carichi di lavoro VMware on-premise ad Amazon Elastic VMware Service utilizzando il consulente per la migrazione, ottimizzando i costi e ottenendo un maggiore controllo sul tuo ambiente VMware senza dover riorganizzare o riconfigurare le applicazioni.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Crea un piano di distribuzione per Amazon EVS utilizzando il consulente per la migrazione"]



=== Carichi di lavoro Genai



==== Supporto per fonti di dati ospitate su file system NFS/SMB generici

Ora è possibile aggiungere un'origine dati da una condivisione SMB o NFS generica. Ciò consente di includere file archiviati su volumi ospitati da file system diversi da Amazon FSx per NetApp ONTAP.

https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html#add-data-sources-to-the-knowledge-base["Aggiungere fonti di dati a una knowledge base"]

https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["Aggiungere origini dati a un connettore"]



=== Installazione e amministrazione



==== Aggiornamento delle autorizzazioni per i database

La seguente autorizzazione è ora disponibile in modalità _sola lettura_ per i database:  `cloudwatch:GetMetricData` .

https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



==== Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP

Il servizio di notifica di BlueXP Workload Factory consente a Workload Factory di inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).

https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche di fabbrica del carico di lavoro BlueXP"]



== 2025-06-16



=== Carichi di lavoro dei costruttori



==== Supporto per clonazione

Ora è possibile clonare un progetto nella fabbrica di carichi di lavoro BlueXP per Builders. Quando si clona un progetto, Builders crea un nuovo progetto da uno snapshot, con la stessa configurazione dell'originale. La clonazione è utile per creare rapidamente progetti simili o per scopi di test. È possibile montare il nuovo clone del progetto seguendo le istruzioni in Builders.

https://docs.netapp.com/us-en/workload-builders/version-projects.html["Gestisci le versioni della fabbrica di carichi di lavoro BlueXP per i progetti Builder"]



== 2025-06-08



=== Amazon FSX per NetApp ONTAP



==== Nuova analisi ben progettata e supporto per la risoluzione dei problemi

La gestione automatica della capacità per i file system FSx per ONTAP è ora inclusa come analisi della configurazione nella dashboard dello stato ben progettata.

Inoltre, Workload Factory ora supporta la correzione dei seguenti problemi di configurazione:

* Soglia di capacità SSD
* Tiering dei dati
* Istantanee locali pianificate
* FSx per backup ONTAP
* Replica remota dei dati
* Efficienza dello storage
* Gestione automatica della capacità


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Risolvi i problemi di configurazione"]



== 2025-06-03



=== Amazon FSX per NetApp ONTAP



==== Miglioramento dell'aumento automatico del volume

Ora puoi impostare l'aumento automatico delle dimensioni dei tuoi volumi in modo che le dimensioni del volume possano aumentare oltre le dimensioni previste in base alle esigenze aziendali e ai requisiti delle applicazioni.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["Attiva la crescita automatica del volume"]



==== Aggiornamento dell'analisi ben progettata

Workload Factory ora analizza i file system FSx for ONTAP per verificare se le efficienze di storage, tra cui compattazione dei dati, compressione e deduplicazione, vengono sfruttate. L'efficienza di storage misura l'efficacia con cui i file system utilizzano lo spazio disponibile.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato delle efficienze di archiviazione"]



==== Miglioramenti della dashboard di archiviazione

A partire da oggi, aprendo il carico di lavoro Storage dalla console di Workload Factory, verrà visualizzata la *Dashboard*. La dashboard di nuova progettazione offre una visione olistica dei sistemi FSx for ONTAP, inclusi il numero di file system, la capacità totale degli SSD, la panoramica dello stato di architettura, la panoramica della protezione dei dati e lo stato della relazione di replica.



==== Miglioramenti della scheda Volumi

Il carico di lavoro Storage ha apportato miglioramenti alla scheda Volumi all'interno di un file system FSx for ONTAP nella console della factory del carico di lavoro. I miglioramenti includono:

* *Nuove schede*: capacità SSD, pool di capacità e protezione autonoma da ransomware (ARP)
* *Nuove colonne*: Distribuzione della capacità, Capacità SSD utilizzata, Pool di capacità utilizzata ed Efficienza SSD




==== Aggiornamento dell'efficienza di archiviazione per la creazione di volumi

Quando si crea un nuovo volume, le efficienze di archiviazione, tra cui la compattazione dei dati, la compressione e la deduplicazione, sono abilitate per impostazione predefinita.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crea un nuovo volume nella fabbrica dei carichi di lavoro"]



=== Workload dei database



==== Rilevamento di PostgreSQL e Oracle

Ora puoi individuare le istanze che eseguono database PostgreSQL e distribuzioni di database Oracle nel tuo account AWS all'interno della console di Workload Factory. Le istanze individuate appariranno nell'inventario dei database.



==== Aggiornata la terminologia "Ottimizzazione"

Precedentemente chiamata "Ottimizzazione", la Workload Factory ora utilizza "problemi ben progettati" e "stato ben progettato" per descrivere l'analisi delle configurazioni del database e "correzione" per descrivere la soluzione per le opportunità di migliorare le configurazioni del database al fine di soddisfare le raccomandazioni delle best practice.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Analisi della configurazione per ambienti di database nella fabbrica dei carichi di lavoro"]



==== Miglioramento dell'onboarding per le istanze

Invece di utilizzare i termini "non rilevato", "non gestito" o "gestito" per la gestione delle istanze, Workload Factory ora utilizza "registra" per l'onboarding delle istanze. Il nuovo processo di registrazione include l'autenticazione e la preparazione delle istanze, in modo da poter creare, monitorare, analizzare e correggere le risorse nelle configurazioni del database all'interno della console di Workload Factory. La fase di preparazione nel processo di registrazione indica se le istanze sono pronte per la gestione.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestione delle istanze"]



=== Carichi di lavoro Genai



==== Tracker disponibile per il monitoraggio e il monitoraggio delle operazioni

La funzionalità di monitoraggio Tracker è ora disponibile in GenAI. È possibile utilizzare Tracker per monitorare e tracciare l'avanzamento e lo stato delle operazioni in sospeso, in corso e completate, rivedere i dettagli delle attività e delle sottoattività delle operazioni, diagnosticare eventuali problemi o errori, modificare i parametri per le operazioni non riuscite e riprovare le operazioni non riuscite.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Monitorare le operazioni del carico di lavoro con Tracker nella fabbrica del carico di lavoro BlueXP"]



==== Scegli un modello di riclassificazione per una knowledge base

Ora puoi aumentare la pertinenza dei risultati delle query riclassificate selezionando un modello di riclassificazione specifico da utilizzare con una knowledge base. GenAI supporta i modelli Cohere Rerank e Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



== 2025-05-04



=== Workload dei database



==== Miglioramenti alla dashboard

* Le viste per account e aree multiple sono disponibili mentre si naviga tra le schede nella console di fabbrica del carico di lavoro di BlueXP . Le nuove viste migliorano la gestione, il monitoraggio e l'ottimizzazione delle risorse.
* Dal riquadro *potenziali risparmi* della dashboard, potrai rivedere rapidamente ciò che potresti risparmiare passando ad FSX per ONTAP da Amazon Elastic Block Store o Amazon FSX per Windows file Server.




==== Scansione ad hoc disponibile per le configurazioni di database

La farm di workload BlueXP  per i database analizza automaticamente le istanze gestite di Microsoft SQL Server con FSX per lo storage ONTAP per rilevare potenziali problemi di configurazione. Ora, oltre alla scansione giornaliera, è possibile eseguire la scansione in qualsiasi momento.



==== Rimozione dei record di valutazione in loco

Dopo aver esaminato i risparmi per un host on-premise di Microsoft SQL Server, è possibile rimuovere il record dell'host on-premise dalla fabbrica dei workload BlueXP .



==== Miglioramenti all'ottimizzazione



===== Pulitura dei cloni

La valutazione e la correzione del cleanup dei cloni identificano e gestiscono cloni vecchi e costosi. I cloni più vecchi di 60 giorni possono essere aggiornati o eliminati dalla console della workload Factory di BlueXP .



===== Posticipare e respingere l'analisi della configurazione

Alcune configurazioni potrebbero non essere applicabili agli ambienti di database in uso. È ora possibile posticipare di 30 giorni una particolare analisi della configurazione o chiudere l'analisi.



==== Rimozione dei record di valutazione in loco

Dopo aver esaminato i risparmi per un host on-premise di Microsoft SQL Server, è possibile rimuovere il record dell'host on-premise dalla fabbrica dei workload BlueXP .



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Workload VMware



==== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa release della fabbrica di workload BlueXP  per VMware presenta i seguenti miglioramenti per l'esperienza con il Migration ADVISOR di Amazon EC2:

*Informazioni sull'infrastruttura dati NetApp come origine dati*: Workload Factory si connette direttamente con NetApp Data Infrastructure Insights per raccogliere informazioni sulla distribuzione VMware quando si utilizza il data collector del Migration ADVISOR EC2.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Carichi di lavoro Genai



==== Supporto per NetApp Connector per Amazon Q Business

Questa versione di GenAI introduce il supporto per NetApp Connector per Amazon Q Business, consentendo di creare connettori per Amazon Q Business. Sfrutta in modo rapido e semplice l'assistente ai aziendale Amazon Q con una configurazione iniziale inferiore rispetto alla creazione di una knowledge base Genai per Amazon Bedrock.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Crea un connettore NetApp per Amazon Q Business"]



==== Supporto di modelli di chat avanzati

GenAI supporta ora i seguenti modelli di chat aggiuntivi per le knowledge base:

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modelli Mistral ai"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modelli di testo Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modelli meta Llama"^]
* link:https://docs.ai21.com/["Modelli Jamba 1,5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modelli Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modelli Deepseek"^]


GenAI supporta i modelli di ciascun provider supportati da Amazon Bedrock: link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modelli di base supportati in Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Installazione e amministrazione



==== Supporto di completamento automatico di CloudShell

Quando si utilizza la fabbrica CloudShell del carico di lavoro di BlueXP , è possibile iniziare a digitare un comando e premere il tasto Tab per visualizzare le opzioni disponibili. Se esistono più possibilità, l'interfaccia CLI visualizza un elenco di suggerimenti. Questa funzionalità migliora la produttività riducendo al minimo gli errori e accelerando l'esecuzione dei comandi.



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Carichi di lavoro dei costruttori



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



== 2025-03-30



=== Workload VMware



==== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa release della fabbrica di workload BlueXP  per VMware presenta diversi miglioramenti all'esperienza del Migration Advisor di Amazon EC2:

* *Guida avanzata all'assegnazione dei volumi*: Le informazioni sull'assegnazione dei volumi nei passaggi "Classify" e "Package" del Migration ADVISOR EC2 offrono una leggibilità e una fruibilità migliorate. Vengono visualizzate informazioni più utili su ciascun volume, che consentono di identificare meglio i volumi e di determinarne l'assegnazione.
* *Miglioramenti all'efficienza degli script di raccolta dati*: Lo script di raccolta dati del Migration ADVISOR EC2 ottimizza l'utilizzo della CPU durante la raccolta dei dati per implementazioni VM di dimensioni inferiori.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]



=== Installazione e amministrazione



==== CloudShell riporta risposte di errore generate dall'ai per i comandi CLI di ONTAP

Quando si utilizza CloudShell, ogni volta che si invia un comando CLI di ONTAP e si verifica un errore, è possibile ottenere risposte agli errori generate dall'intelligenza artificiale che includono una descrizione del guasto, la causa del guasto e una risoluzione dettagliata.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilizzare CloudShell"]



==== iam:aggiornamento autorizzazioni SimulatePermissionPolicy

Ora puoi gestire `iam:SimulatePrincipalPolicy` il permesso dalla console workload Factory quando Aggiungi ulteriori credenziali di account AWS o Aggiungi una nuova funzionalità del workload come il workload Genai.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



== 2024-12-01



=== Carichi di lavoro dei costruttori



==== Rilascio iniziale del carico di lavoro dei costruttori

BlueXP  workload Factory for Builders semplifica l'utilizzo e l'accesso delle versioni software, eliminando la necessità di strumenti o script personalizzati. Consente di utilizzare le versioni software come cloni istantanei integrati con Perforce Helix Core come spazio di lavoro comodo per i processi di sviluppo, risparmiando tempo e risorse.

La release iniziale include la capacità di gestire progetti e aree di lavoro e automatizzare azioni con Codebox. È inoltre possibile integrare i costruttori con Perforce Helix Core, in modo da poter gestire diverse versioni di ciascun progetto e passare rapidamente da un progetto all'altro.
