---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory. 
---
= Modifiche recenti in NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti apportate ai carichi di lavoro che fanno parte di NetApp Workload Factory.



== 6 aprile 2026



=== Workload dei database



==== Analisi ben progettata per Oracle

L'analisi ben strutturata include le seguenti nuove configurazioni per Oracle:

* *Aggiornamenti critici delle patch Oracle*: verifica la presenza di patch di sicurezza mancanti per le installazioni di database Oracle autogestite supportate.
* *Replica tra regioni*: verifica se la replica tra regioni (CRR) è abilitata per i file system FSx for ONTAP che ospitano database Oracle.
* *Snapshot coerenti con l'applicazione*: verifica se il database Oracle è protetto da snapshot coerenti con l'applicazione con NetApp SnapCenter.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



==== Valutazione una tantum per Oracle

Workload Factory offre ora una valutazione una tantum per analizzare le configurazioni delle tue implementazioni di database Oracle ogni volta che ne hai bisogno: nuove implementazioni, post-migrazione, risoluzione dei problemi e altro ancora. Riceverai consigli per aiutarti a ottimizzare le configurazioni delle tue implementazioni e a rispettare le best practice. Questa è la tua opportunità per utilizzare la funzionalità ben progettata senza dover completare l'intero processo di configurazione. Puoi valutare i tuoi database senza memorizzare le credenziali in Workload Factory, registrare risorse di database o configurare connessioni esterne.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Esegui una valutazione una tantum delle tue implementazioni di database Oracle"]



==== Risparmio sui costi migliorato per diversi database Oracle

Abbiamo migliorato l'analisi del risparmio sui costi per Oracle al fine di fornire una soluzione storage consolidata per diversi database Oracle on-premises su un unico file system FSx for ONTAP. Questo consolidamento ottimizza i costi di storage riducendo il numero di file system necessari per più database, portando a un maggiore risparmio sui costi.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Scopri le possibilità di risparmio per i database rilevati su Oracle on-premises"]



== 09 marzo 2026



=== Workload VMware



==== Introduzione del supporto di migration advisor per Google Cloud VMware Engine

NetApp Workload Factory ora supporta Google Cloud VMware Engine. Puoi migrare i tuoi carichi di lavoro VMware on-premises su Google Cloud VMware Engine utilizzando Google Cloud NetApp Volumes come datastore NFS esterni, ottimizzando i costi e consentendo un maggiore controllo sul tuo ambiente VMware senza dover riorganizzare o riconfigurare le tue applicazioni.

Il consulente per la migrazione di Google Cloud VMware Engine fornisce:

* Dimensionamento e progettazione automatizzati dei cluster Google Cloud VMware Engine con supporto dei tipi di nodo VE1 e VE2
* Ottimizzazione del layout della VM tra i datastore interni vSAN e i datastore NFS esterni Google Cloud NetApp Volumes.
* Confronto dettagliato dei costi e analisi del TCO tra configurazioni solo vSAN e configurazioni potenziate con Google Cloud NetApp Volumes.
* Supporto per i livelli di servizio Standard, Premium ed Extreme di Google Cloud NetApp Volumes.
* Distribuzione Infrastructure-as-Code con Terraform per il provisioning automatico.




== 02 marzo 2026



=== Workload dei database



==== Valutazione una tantum per SQL Server

Workload Factory offre ora una valutazione una tantum per analizzare le configurazioni delle distribuzioni del database SQL Server ogni volta che ne hai bisogno: nuove distribuzioni, post-migrazione, risoluzione dei problemi e altro ancora. Riceverai consigli per aiutarti a ottimizzare le configurazioni delle tue implementazioni e a rispettare le best practice. Questa è la tua opportunità per utilizzare la funzionalità ben progettata senza dover completare l'intero processo di configurazione. Puoi valutare i tuoi database senza memorizzare le credenziali in Workload Factory, registrare risorse di database o configurare connessioni esterne.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Esegui una valutazione una tantum delle distribuzioni del database"]



==== Supporto di registrazione per gruppi di disponibilità Always On su Microsoft SQL Server e Data Guard su database Oracle

Ora è possibile individuare e registrare istanze di Microsoft SQL Server con il modello di distribuzione Always On availability group (AOAG) e database Oracle con il modello di distribuzione Data Guard nel carico di lavoro Databases di NetApp Workload Factory. Questo miglioramento consente una migliore gestione delle risorse di SQL Server e Oracle all'interno della console di Workload Factory.

Dopo aver registrato le istanze AOAG e i database Data Guard, puoi sfruttare le varie funzionalità di NetApp Workload Factory per database, come la visualizzazione dei dettagli delle risorse e l'analisi dei registri degli errori.

Workload Factory for Databases supporta anche l'analisi ben progettata per le istanze di Microsoft SQL Server con il modello di distribuzione AOAG. Puoi analizzare le configurazioni delle tue istanze di SQL Server in un gruppo di disponibilità e ricevere raccomandazioni per ottimizzare le configurazioni di distribuzione e rispettare le best practice. Registra le istanze AOAG per abilitare questa funzionalità.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html#register-a-sql-server-instance["Registra le risorse in Workload Factory for Databases"]



==== Analisi ben progettata per Oracle

L'analisi ben strutturata include *patch del sistema operativo* per Oracle per verificare se hai le patch più recenti sul sistema operativo e dirti come installarle.

Inoltre, l'analisi ben progettata per Oracle ti avvisa quando una configurazione, come il layout di storage, presenta dipendenze da altre configurazioni. La notifica ti indica quali azioni intraprendere per ottimizzare le configurazioni collegate, in modo che tutte le raccomandazioni che forniamo siano ottimali.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



==== Analisi dei costi e pianificazione della migrazione degli ambienti di database on-premises Oracle

Workload Factory for Databases ora analizza e ti aiuta a pianificare la migrazione del database Oracle on-premises ad Amazon FSx for NetApp ONTAP. Puoi utilizzare il calcolatore di risparmio per stimare il costo di esecuzione del tuo ambiente di database Oracle on-premises nel cloud e consultare le raccomandazioni per la migrazione del tuo ambiente di database on-premises al cloud.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Esplora i risparmi per gli ambienti di database on-premises"]



==== Nuovo segnalibro Ask Me disponibile in Workload Factory

Abbiamo aggiunto un nuovo segnalibro Ask Me in ogni schermata della console di Workload Factory. Questo miglioramento rende più facile e veloce accedere ad Ask Me ogni volta che hai bisogno di aiuto. Ask Me è il nostro assistente AI, che ti consente di porre domande sui tuoi ambienti di carico di lavoro, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti.

Puoi aprire Ask Me da qualsiasi pagina cliccando sul nuovo segnalibro. Si avvia Ask Me in un pannello laterale senza interrompere il tuo lavoro attuale e offre spiegazioni rapide e raccomandazioni relative a ciò che stai facendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Scopri di più su Ask Me"^]



== 01 marzo 2026



=== Amazon FSX per NetApp ONTAP



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Capacità SSD sottoutilizzata: verifica se il livello di capacità SSD è sottoutilizzato e consiglia di ridurre la capacità SSD per ottimizzare i costi.
* Pianifica backup dei volumi: NetApp Workload Factory migliora le raccomandazioni di configurazione e aggiunge opzioni per attivare il backup di FSx for ONTAP o AWS Backup. FSx for ONTAP backup applica una policy predefinita a tutti i volumi in un file system, creando backup giornalieri conservati fino a 90 giorni. AWS Backup consente di scegliere periodi di conservazione diversi per ciascun volume nel piano di backup.




==== Workload Factory supporta il caso d'uso AI & ML per la replica

Workload Factory supporta la replica dei dati ONTAP locali su FSx for ONTAP e la creazione di punti di accesso S3 per i servizi di AWS Artificial Intelligence (AI) e machine learning (ML) per accelerare i flussi di lavoro AI/ML.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replicare i dati on-premises per casi d'uso di AI e ML"]



==== Modifica dei punti di accesso S3 esistenti

È possibile modificare l'utente e il tipo di utente per un punto di accesso S3 esistente collegato a un volume. È anche possibile abilitare o disabilitare i metadati per il punto di accesso.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Modifica i punti di accesso S3 in NetApp Workload Factory"]



==== Aggiunto diagramma dello storage a blocchi

Se utilizzi storage a blocchi, puoi visualizzare il diagramma dello storage a blocchi per vedere come i dispositivi a blocchi si connettono ai nodi e agli igroup. Il diagramma ti aiuta a comprendere e gestire il tuo storage a blocchi.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html["Gestire storage a blocchi in NetApp Workload Factory"]



==== Aggiornamento della funzionalità di gestione automatica della capacità

Questo aggiornamento separa la funzionalità in due funzionalità distinte: gestione automatica della capacità e notifiche sulla capacità.

La gestione automatica della capacità aggiunge o rimuove automaticamente la capacità del file system per mantenere prestazioni ottimali. Le nuove opzioni includono modalità incrementale e adattiva. In modalità incrementale, il sistema aumenta la capacità di un importo fisso alle soglie; in modalità adattiva, utilizza dati storici per prevedere e regolare la capacità.

Le notifiche sulla capacità ti avvisano ogni volta che si verifica una modifica della capacità e quando i file system raggiungono i limiti impostati, così puoi gestire lo storage prima che si verifichino problemi.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Scopri la gestione automatica della capacità e le notifiche di capacità in NetApp Workload Factory"]



==== Nuovo segnalibro Ask Me disponibile in Workload Factory

Abbiamo aggiunto un nuovo segnalibro Ask Me in ogni schermata della console di Workload Factory. Questo miglioramento semplifica e velocizza l'accesso ad Ask Me ogni volta che hai bisogno di aiuto. Ask Me è il nostro assistente AI. Puoi porre domande sui tuoi ambienti di workload, ottenere informazioni personalizzate e rivedere le conversazioni precedenti.

Puoi aprire Ask Me da qualsiasi pagina cliccando sul nuovo segnalibro. Si avvia Ask Me in un pannello laterale senza interrompere il tuo lavoro attuale e offre spiegazioni rapide e raccomandazioni relative a ciò che stai facendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Scopri di più su Ask Me"^]



=== Workload VMware



==== Nuovo segnalibro Ask Me disponibile in Workload Factory

Abbiamo aggiunto un nuovo segnalibro Ask Me in ogni schermata della console di Workload Factory. Questo miglioramento rende più facile e veloce accedere ad Ask Me ogni volta che hai bisogno di aiuto. Ask Me è il nostro assistente AI, che ti consente di porre domande sui tuoi ambienti di carico di lavoro, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti.

Puoi aprire Ask Me da qualsiasi pagina cliccando sul nuovo segnalibro. Si avvia Ask Me in un pannello laterale senza interrompere il tuo lavoro attuale e offre spiegazioni rapide e raccomandazioni relative a ciò che stai facendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Scopri di più su Ask Me"^]



=== Installazione e amministrazione



==== Nuovo segnalibro Ask Me disponibile in Workload Factory

Abbiamo aggiunto un nuovo segnalibro Ask Me in ogni schermata della console di Workload Factory. Questo miglioramento rende più facile e veloce accedere ad Ask Me ogni volta che hai bisogno di aiuto. Ask Me è il nostro assistente AI, che ti consente di porre domande sui tuoi ambienti di carico di lavoro, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti.

Puoi aprire Ask Me da qualsiasi pagina cliccando sul nuovo segnalibro. Si avvia Ask Me in un pannello laterale senza interrompere il tuo lavoro attuale e offre spiegazioni rapide e raccomandazioni relative a ciò che stai facendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Scopri di più su Ask Me"]



=== Carichi di lavoro EDA



==== Dashboard panoramica per la gestione dello storage EDA

In qualità di amministratore IT che gestisce decine di file system FSx for ONTAP, puoi utilizzare la dashboard di panoramica per rispondere a domande operative comuni sullo stato del cluster, l'utilizzo e il posizionamento dei volumi.

La dashboard di panoramica include:

* *Stato di integrità del cluster*: informazioni riepilogate nella parte superiore della dashboard che evidenziano performance, capacità, disponibilità e protezione, ed eventi di sicurezza nei tuoi cluster.
* *Tabella dei cluster*: una tabella ricercabile, filtrabile e impaginata che mostra la capacità SSD, il pool di capacità e le metriche di throughput per cluster, con supporto per la personalizzazione delle colonne e l'esportazione CSV.


La precedente dashboard principale è ora accessibile nella scheda *Project*. Le schede EDA sono ora ordinate: Panoramica, Latenza, Project, CI/CD.

https://docs.netapp.com/us-en/workload-eda/task-use-overview-dashboard.html["Scopri di più sulla dashboard di overview"^].



==== Analisi automatizzata della latenza

L'analisi della latenza ora include un'analisi di base automatizzata. Quando vengono rilevati eventi di latenza, il sistema analizza automaticamente le metriche del centro di ritardo QoS di ONTAP per identificare la fonte dei problemi di latenza.

L'analisi di base valuta le policy QoS, le prestazioni del disco, i problemi di rete e le configurazioni del cluster per fornire informazioni immediate nella colonna Dettagli della tabella degli eventi di latenza.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html#understanding-basic-analysis["Scopri di più sull'analisi di latenza di base"^].



==== Nuovo segnalibro Ask Me disponibile in Workload Factory

Abbiamo aggiunto un nuovo segnalibro Ask Me in ogni schermata della console di Workload Factory. Questo miglioramento rende più facile e veloce accedere ad Ask Me ogni volta che hai bisogno di aiuto. Ask Me è il nostro assistente AI, che ti consente di porre domande sui tuoi ambienti di carico di lavoro, ottenere informazioni personalizzate direttamente dal tuo ambiente e fare riferimento a conversazioni precedenti.

Puoi aprire Ask Me da qualsiasi pagina cliccando sul nuovo segnalibro. Si avvia Ask Me in un pannello laterale senza interrompere il tuo lavoro attuale e offre spiegazioni rapide e raccomandazioni relative a ciò che stai facendo.

link:https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html#features["Scopri di più su Ask Me"^]



== 16 febbraio 2026



=== Amazon FSX per NetApp ONTAP



==== Supporto per la migrazione delle storage VM

NetApp Workload Factory ora supporta la migrazione per le storage VM. Questa funzionalità consente la migrazione dei dati e delle configurazioni del sistema storage ONTAP da sistemi ONTAP on-premises o da file system FSx for ONTAP di prima generazione a file system FSx for ONTAP di seconda generazione. È possibile replicare i dati e le impostazioni di configurazione delle storage VM per spostarsi nel nuovo file system con tempi di inattività e interruzioni minimi per utenti e applicazioni.

Per utilizzare questa funzionalità, link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["creare una relazione di replicazione"] e selezionare *Migrazione* come caso d'uso. Per completare il processo di migrazione, è necessario link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html#cut-over-replication-for-migration-use-cases["cutover della storage VM e dei suoi volumi replicati"] immediatamente per migrare in modo permanente i dati e le impostazioni di configurazione della storage VM nel file system FSx for ONTAP di destinazione.



== 02 febbraio 2026



=== Workload dei database



==== Maggiore risparmio sui costi per diversi host di database su Microsoft SQL Server in locale

L'analisi dei risparmi sui costi per Microsoft SQL Server nello storage on-premises è stata migliorata per fornire una soluzione storage consolidata per diversi host di database su un unico file system FSx for ONTAP. Questo consolidamento ottimizza i costi di storage riducendo il numero di file system necessari per più host di database, portando a un maggiore risparmio sui costi.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html#explore-savings-for-detected-hosts["Esplora i risparmi per gli host rilevati su Microsoft SQL Server on-premises"]



==== Analisi ben progettata per Oracle

L'analisi ben progettata include quattro nuove sotto-valutazioni per l'analisi della configurazione dello storage per Oracle: abilitazione dNFS, risoluzione IP coerente dNFS, file di configurazione dNFS e dNFS `nosharecache`. Queste valutazioni riguardano l'abilitazione e la configurazione di Direct NFS (dNFS) per l'ambiente Oracle, che bypassa il client NFS ed esegue operazioni sui file NFS direttamente su un server NFS, migliorando le prestazioni di I/O e riducendo il carico sull'host e sul sistema storage perché l'I/O viene eseguito in modo più efficiente.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate in Workload Factory"]



== 01 febbraio 2026



=== Amazon FSX per NetApp ONTAP



==== La home page include problemi well-architected ed eventi EMS per Storage

La home page di NetApp Workload Factory include un riquadro Focus in cui vengono visualizzati i problemi ben progettati e gli eventi del sistema di gestione delle emergenze (EMS) di FSx for ONTAP per i tuoi carichi di lavoro. Da lì, puoi navigare al carico di lavoro Storage per visualizzare lo stato ben progettato o gli eventi di tutti i file system FSx for ONTAP nel tuo ambiente di storage.



==== Supporto per la replica dei dati on-premises utilizzando un punto di accesso S3

Workload Factory supporta la replica dei dati ONTAP on-premises sul cloud per l'integrazione con AWS GenAI, ML e analytics. Puoi replicare i tuoi dati on-premises su un volume NFS o SMB/CIFS utilizzando un access point S3.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replica i dati on-premises utilizzando un access point S3"]



==== Miglioramenti del punto di accesso S3 in Storage

Sono stati apportati diversi miglioramenti alle funzionalità di gestione degli access point S3 nel carico di lavoro Storage per NetApp Workload Factory. È possibile inserire i dettagli della configurazione di rete per gli access point S3 e aggiungere tag agli access point S3. Ulteriori miglioramenti includono la possibilità di visualizzare i dettagli del bucket S3 ed eseguire più azioni per la gestione degli access point S3.



===== Dettagli del bucket S3 disponibili in Storage

Con i metadati abilitati per i punti di accesso S3, NetApp Workload Factory analizza automaticamente i bucket AWS S3 e popola le tabelle S3 per fornirti un'istantanea chiara di tutti gli oggetti, dei loro metadati, attributi e tag. L'accesso a questi dettagli ti aiuta a mantenere controllo, visibilità e fiducia nei dati di cui sei responsabile, riducendo al contempo l'overhead operativo.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Visualizza i dettagli per i punti di accesso S3 nei file system FSx for ONTAP"]



===== Operazioni di gestione aggiuntive per i punti di accesso S3

NetApp Workload Factory offre operazioni di gestione aggiuntive per i punti di accesso S3. Puoi visualizzare i dettagli dei punti di accesso, modificare i punti di accesso S3 esistenti e aggiungere o rimuovere tag dei punti di accesso S3 dall'interfaccia di NetApp Workload Factory, semplificando le attività di gestione dello storage a oggetti.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html["Gestire i punti di accesso S3 in NetApp Workload Factory"]



==== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Ottimizza le dimensioni del volume della cache: verifica se il dimensionamento automatico e lo scrubbing sono abilitati sui volumi della cache per mantenere le dimensioni ottimali e concentrare la cache sui dati più importanti con la massima efficienza.
* Dispositivi a blocchi inattivi: consiglia di archiviare i dati del dispositivo a blocchi o di eliminare un dispositivo a blocchi se non è stato utilizzato per sette giorni consecutivi.
* Reporting logico della storage VM: verifica se l'impostazione di reporting predefinita per una storage VM è impostata su logica, il che fornisce una migliore visibilità sull'utilizzo dello storage a livello di volume.




==== Schede aggiuntive per block devices

Sono state aggiunte tre nuove schede alla scheda Dispositivi a blocchi nel carico di lavoro Storage per fornire informazioni rapide sull'utilizzo e sullo stato di protezione dei dispositivi a blocchi:

* Efficienze dello storage: mostra la capacità di storage utilizzata e disponibile; la capacità utilizzata è suddivisa tra livelli di storage SSD e capacity pool.
* Dispositivi protetti: mostra la percentuale di dispositivi a blocchi con snapshot, replica remota, NetApp Autonomous Ransomware Protection (ARP/AI) e backup.
* Dispositivi orfani: mostra se qualche dispositivo a blocchi non è stato utilizzato per sette giorni consecutivi, aiutandoti a identificare e gestire efficacemente le risorse inutilizzate. Da qui, puoi link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html#archive-the-data-of-an-inactive-block-device["recupera spazio per i dispositivi a blocchi non utilizzati"].




==== Supporto per la creazione e la gestione del gruppo di initiator

NetApp Workload Factory supporta la creazione e la gestione di gruppi di initiator (igroups) per lo storage a blocchi nei file system FSx for ONTAP. I gruppi di initiator collegano i dispositivi a blocchi (LUN) alle risorse di calcolo autorizzate ad accedervi, fornendo un livello di autorizzazione per lo storage a blocchi in ambienti SAN.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-igroup.html["Creare un initiator group in NetApp Workload Factory"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["Gestisci i gruppi di initiator esistenti in NetApp Workload Factory"]




=== Workload VMware



==== Analisi well-architected per Amazon Elastic VMware Service

Workload Factory ora fornisce un'analisi automatizzata well-architected per i tuoi ambienti Amazon Elastic VMware Service (EVS). Le scansioni giornaliere identificano disallineamenti di configurazione e offrono raccomandazioni dettagliate per la remediation, aiutandoti a mantenere operatività, sicurezza ed efficienza dei costi ottimali.

Le scansioni vengono eseguite utilizzando le API AWS—non sono necessarie credenziali vSphere o connettività vCenter. I risultati sono disponibili nella nuova scheda *Well-architected status* all'interno dei dettagli dell'ambiente EVS.

Questa release include approfondimenti su:

* *Stato di protezione da arresto/terminazione dell'istanza*: identifica i nodi EVS senza protezione da arresto o terminazione EC2. L'arresto o la terminazione dei nodi EVS dalla console EC2 può causare la non disponibilità o la perdita di dati della macchina virtuale.
* *Allineamento del posizionamento delle partizioni dei nodi del cluster*: rileva disallineamenti di partizionamento che potrebbero causare perdite significative di potenza di elaborazione o tempi di inattività in caso di guasto di una partizione all'interno di una AWS Availability Zone. Ogni insight include livelli di gravità, risultati dettagliati con informazioni sulle risorse interessate e procedure di correzione dettagliate basate sulle AWS best practice.


link:view-evs-well-architected.html["Implementare configurazioni ben architettate"]



=== Installazione e amministrazione



==== Aggiornamenti ben progettati

NetApp Workload Factory include la valutazione ben progettata per i carichi di lavoro Elastic VMware Service (EVS) e aggiunge nuove configurazioni per i carichi di lavoro Storage e Database.

* *Carichi di lavoro VMware* NetApp Workload Factory fornisce best practice e raccomandazioni per l'esecuzione di carichi di lavoro Amazon Elastic VMware Service (EVS) ben architettati.
+
link:https://docs.netapp.com/us-en/workload-vmware/view-evs-well-architected.html["Implementare configurazioni EVS ben architettate"^]

* *Carichi di lavoro di archiviazione* Sono state aggiunte diverse nuove configurazioni alla funzionalità ben progettata nel carico di lavoro di archiviazione, in modo da avere una visione più approfondita sulle performance dello storage e sui costi.
+
** Reporting logico della Storage VM
** Ottimizza la dimensione del volume della cache
** Dispositivi a blocchi orfani
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementare configurazioni di file system ben progettate per i carichi di lavoro Storage"^]



* *Carichi di lavoro del database* Workload Factory for Databases include una nuova configurazione dello storage per Oracle per abilitare e configurare Direct NFS (dNFS) per migliorare le prestazioni di I/O e ridurre il carico sull'host e sul sistema storage.
+
** Abilitazione dNFS
** Risoluzione IP coerente dNFS
** file di configurazione dNFS
** dNFS `nosharecache`
+
link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare carichi di lavoro di database ben progettati"^]







==== Nuove autorizzazioni per Storage

Sono state aggiunte nuove autorizzazioni al workload Storage per miglioramenti nella gestione dei punti di accesso S3.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



=== Carichi di lavoro EDA



==== Filtraggio della dashboard migliorato con tag personalizzabili

Ora puoi configurare fino a cinque filtri personalizzati sulla dashboard EDA in base ai tuoi tag AWS. Ogni filtro personalizzato include un nome etichetta, una chiave di tag AWS e un tipo di selezione (singola o multipla).

La selezione multipla consente di selezionare più valori contemporaneamente, mentre la selezione singola limita la selezione a un solo valore alla volta. I filtri personalizzati vengono visualizzati nell'ordine in cui li configuri, rendendo facile organizzare i filtri utilizzati più frequentemente.

Se non configuri filtri personalizzati, i filtri predefiniti (file system, tipo di volume e intervallo di tempo) rimangono disponibili così puoi continuare a visualizzare e interagire con i tuoi dashboard.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html["Scopri di più sulla configurazione dei filtri personalizzati"^].



==== Visualizzazione dei dettagli del volume per un'analisi granulare delle performance

La dashboard ora offre due modalità di visualizzazione: Total view e Volume view. La Total view mostra metriche aggregate su tutti i volumi, mentre la Volume view mostra le performance individuali dei primi 10 volumi nel tempo.

Nella vista Volume, i suggerimenti interattivi al passaggio del mouse forniscono informazioni dettagliate per ciascun volume, inclusi nome del volume, metriche e valori specifici per il tempo. Quando gli stessi volumi sono presenti in più componenti, la codifica a colori coerente semplifica il monitoraggio di volumi specifici tra diverse metriche.

https://docs.netapp.com/us-en/workload-eda/task-configure-dashboard.html#view-volume-details["Scopri di più sulla visualizzazione dei dettagli del volume"^].



==== Analisi della latenza per il monitoraggio proattivo delle performance

L'analisi della latenza consente di monitorare la latenza di lettura e scrittura dei volumi nei file system FSx for ONTAP. È possibile configurare soglie personalizzabili di avviso e di evento critico per identificare in modo proattivo i colli di bottiglia delle performance prima che influiscano sui carichi di lavoro EDA.

La tabella degli eventi di latenza visualizza tutti gli eventi di avviso e critici, consentendo di monitorare le performance del volume e di identificare i volumi che richiedono ottimizzazione.

Questa funzionalità richiede le credenziali AWS ed è accessibile dal menu Latenza nella dashboard EDA.

https://docs.netapp.com/us-en/workload-eda/task-monitor-latency.html["Scopri di più sull'analisi della latenza"^].
