---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, administration, amazon fsx for netapp ontap, databases, genai, vmware' 
summary: Scopri le modifiche più recenti ai carichi di lavoro che fanno parte della fabbrica di carichi di lavoro BlueXP . 
---
= Recenti cambiamenti nella fabbrica di workload BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti ai carichi di lavoro che fanno parte della fabbrica di carichi di lavoro BlueXP .



== 2025-06-03



=== Amazon FSX per NetApp ONTAP



==== Miglioramento dell'aumento automatico del volume

Ora puoi impostare l'aumento automatico delle dimensioni dei tuoi volumi in modo che le dimensioni del volume possano aumentare oltre le dimensioni previste in base alle esigenze aziendali e ai requisiti delle applicazioni.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/edit-volume-autogrow.html["Attiva la crescita automatica del volume"]



==== Aggiornamento dell'analisi ben progettata

Workload Factory ora analizza i file system FSx for ONTAP per verificare se le efficienze di storage, tra cui compattazione dei dati, compressione e deduplicazione, vengono sfruttate. L'efficienza di storage misura l'efficacia con cui i file system utilizzano lo spazio disponibile.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato delle efficienze di archiviazione"]



==== Miglioramenti della dashboard di archiviazione

A partire da oggi, aprendo il carico di lavoro Storage dalla console di Workload Factory, verrà visualizzata la *Dashboard*. La dashboard di nuova progettazione offre una visione olistica dei sistemi FSx for ONTAP, inclusi il numero di file system, la capacità totale degli SSD, la panoramica dello stato di architettura, la panoramica della protezione dei dati e lo stato della relazione di replica.



==== Miglioramenti della scheda Volumi

Il carico di lavoro Storage ha apportato miglioramenti alla scheda Volumi all'interno di un file system FSx for ONTAP nella console della factory del carico di lavoro. I miglioramenti includono:

* *Nuove schede*: capacità SSD, pool di capacità e protezione autonoma da ransomware (ARP)
* *Nuove colonne*: Distribuzione della capacità, Capacità SSD utilizzata, Pool di capacità utilizzata ed Efficienza SSD




==== Aggiornamento dell'efficienza di archiviazione per la creazione di volumi

Quando si crea un nuovo volume, le efficienze di archiviazione, tra cui la compattazione dei dati, la compressione e la deduplicazione, sono abilitate per impostazione predefinita.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Crea un nuovo volume nella fabbrica dei carichi di lavoro"]



=== Workload dei database



==== Rilevamento di PostgreSQL e Oracle

Ora puoi individuare le istanze che eseguono database PostgreSQL e distribuzioni di database Oracle nel tuo account AWS all'interno della console di Workload Factory. Le istanze individuate appariranno nell'inventario dei database.



==== Aggiornata la terminologia "Ottimizzazione"

Precedentemente chiamata "Ottimizzazione", la Workload Factory ora utilizza "problemi ben progettati" e "stato ben progettato" per descrivere l'analisi delle configurazioni del database e "correzione" per descrivere la soluzione per le opportunità di migliorare le configurazioni del database al fine di soddisfare le raccomandazioni delle best practice.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Analisi della configurazione per ambienti di database nella fabbrica dei carichi di lavoro"]



==== Miglioramento dell'onboarding per le istanze host

Invece di utilizzare i termini "non rilevato", "non gestito" o "gestito" per la gestione delle istanze host, Workload Factory ora utilizza "registra" per l'onboarding delle istanze host. Il nuovo processo di registrazione include l'autenticazione e la preparazione delle istanze host, in modo da poter creare, monitorare, analizzare e correggere le risorse nelle configurazioni del database all'interno della console di Workload Factory. La fase di preparazione del processo di registrazione indica se le istanze host sono pronte per la gestione.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestione delle istanze"]



=== Carichi di lavoro Genai



==== Tracker disponibile per il monitoraggio e il monitoraggio delle operazioni

La funzionalità di monitoraggio Tracker è ora disponibile in GenAI. È possibile utilizzare Tracker per monitorare e tracciare l'avanzamento e lo stato delle operazioni in sospeso, in corso e completate, rivedere i dettagli delle attività e delle sottoattività delle operazioni, diagnosticare eventuali problemi o errori, modificare i parametri per le operazioni non riuscite e riprovare le operazioni non riuscite.

link:https://docs.netapp.com/us-en/workload-genai/general/monitor-operations.html["Monitorare le operazioni del carico di lavoro con Tracker nella fabbrica del carico di lavoro BlueXP"]



==== Scegli un modello di riclassificazione per una knowledge base

Ora puoi aumentare la pertinenza dei risultati delle query riclassificate selezionando un modello di riclassificazione specifico da utilizzare con una knowledge base. GenAI supporta i modelli Cohere Rerank e Amazon Rerank.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



== 2025-05-04



=== Amazon FSX per NetApp ONTAP



==== Protezione autonoma dal ransomware per file system FSX per ONTAP

Proteggi i tuoi dati con la protezione autonoma dal ransomware (ARP), una funzionalità che sfrutta l'analisi dei workload negli ambienti NAS (NFS/SMB) per rilevare e informare l'utente in caso di attività anomale che potrebbero essere un attacco ransomware. Quando si sospetta un attacco, ARP crea anche nuove istantanee immutabili da cui è possibile ripristinare i dati.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Proteggi i tuoi dati con la protezione autonoma dal ransomware"]



==== Potenziamento del ribilanciamento dei volumi di FlexGroup

BlueXP  workload Factory introduce la procedura guidata per il ribilanciamento dei volumi FlexGroup con diverse opzioni di layout per il ribilanciamento dei dati in un volume FlexGroup. Il ribilanciamento ridistribuisce i dati in modo uniforme nei volumi dei membri FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Ribilanciare la capacità in un volume FlexGroup"]



==== Implementare le Best practice per un file system FSX per ONTAP

La fabbrica dei carichi di lavoro di BlueXP  fornisce una dashboard in cui puoi esaminare lo stato con l'architettura ideale delle configurazioni del file system. Puoi sfruttare questa analisi per implementare le Best practice per i file system FSX per ONTAP. L'analisi della configurazione del file system include le seguenti configurazioni: Soglia di capacità SSD, snapshot locali pianificate, backup FSX for ONTAP pianificati, tiering dei dati e replica dei dati remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Scopri l'analisi con un'architettura ideale per le configurazioni del file system"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementare le Best practice per i file system"]




==== Opzioni per lo stile di sicurezza del volume a doppio protocollo

È possibile scegliere NTFS o UNIX come stile di protezione per un volume per determinare il metodo a cui gli utenti e le autorizzazioni accedono a un volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Creare un volume"]



==== Miglioramenti alla replica



===== Replica inversa supportata da FSX per ONTAP a on-premise

La replica inversa è ora disponibile da un file system FSX per ONTAP a un cluster ONTAP on-premise dall'interno della console della workload factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Replica inversa"]



===== Replica di un volume di data Protection

Ora puoi replicare i volumi di data Protection.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Replica di un volume di data Protection"]



===== Selezione di più volumi

È disponibile la selezione di più volumi, in modo da poter selezionare esattamente i volumi da replicare.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Creare una relazione di replica"]



===== Etichette di criteri di conservazione a lungo termine

Quando si attiva la conservazione a lungo termine per una relazione di replica, le etichette dei volumi di origine e di destinazione devono corrispondere esattamente. Ora BlueXP  workload Factory può creare automaticamente etichette del volume di origine mancanti.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Creare una relazione di replica"]



==== Il nome del file FSX per ONTAP è visibile nella creazione del volume

Abbiamo migliorato la visibilità dei file system FSX per ONTAP durante la creazione dei volumi. Quando crei un volume, visualizzerai il file system FSX per ONTAP, in modo da sapere esattamente dove viene creato il volume.



==== Account AWS visibile per tutto il workload dello storage

Abbiamo migliorato la visibilità degli account sul workload dello storage. L'account AWS viene visualizzato quando si accede alle schede *volumi*, *Storage VM* e *Replication*.



==== Miglioramenti dell'associazione di collegamento

* È possibile associare rapidamente un collegamento da un file system FSX per ONTAP nella scheda inventario.
* BlueXP  workload Factory ora supporta l'utilizzo di credenziali utente ONTAP alternative per l'associazione dei collegamenti.




==== Supporto di autenticazione link per AWS Secrets Manager

Ora hai la possibilità di utilizzare i segreti di AWS Secrets Manager per autenticare i link in modo da non dover utilizzare le credenziali memorizzate nella fabbrica dei workload BlueXP .



==== Supporto risposta Tracker

Tracker ora fornisce le risposte API in modo da poter vedere l'output dell'API REST relativo all'attività.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Monitoraggio delle operazioni con Tracker"]



==== Convalida della capacità durante il ripristino di un volume da un backup

Quando si ripristina un volume da un backup, la fabbrica del carico di lavoro BlueXP  determina se si dispone di capacità sufficiente per il ripristino e, in caso contrario, può aggiungere automaticamente capacità del livello di storage SSD.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Ripristinare un volume da un backup"]



==== Supporto per credenziali utente ONTAP alternative

Workload Factory ora supporta set alternativi di credenziali ONTAP per la creazione di file system al fine di ridurre al minimo i rischi per la sicurezza. Invece di utilizzare solo l'utente fsxadmin, è possibile selezionare un diverso set di credenziali ONTAP o scegliere di non fornire una password per gli utenti fsxadmin e vsaadmin.



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Workload dei database



==== Miglioramenti alla dashboard

* Le viste per account e aree multiple sono disponibili mentre si naviga tra le schede nella console di fabbrica del carico di lavoro di BlueXP . Le nuove viste migliorano la gestione, il monitoraggio e l'ottimizzazione delle risorse.
* Dal riquadro *potenziali risparmi* della dashboard, potrai rivedere rapidamente ciò che potresti risparmiare passando ad FSX per ONTAP da Amazon Elastic Block Store o Amazon FSX per Windows file Server.




==== Scansione ad hoc disponibile per le configurazioni di database

La farm di workload BlueXP  per i database analizza automaticamente le istanze gestite di Microsoft SQL Server con FSX per lo storage ONTAP per rilevare potenziali problemi di configurazione. Ora, oltre alla scansione giornaliera, è possibile eseguire la scansione in qualsiasi momento.



==== Rimozione dei record di valutazione in loco

Dopo aver esaminato i risparmi per un host on-premise di Microsoft SQL Server, è possibile rimuovere il record dell'host on-premise dalla fabbrica dei workload BlueXP .



==== Miglioramenti all'ottimizzazione



===== Pulitura dei cloni

La valutazione e la correzione del cleanup dei cloni identificano e gestiscono cloni vecchi e costosi. I cloni più vecchi di 60 giorni possono essere aggiornati o eliminati dalla console della workload Factory di BlueXP .



===== Posticipare e respingere l'analisi della configurazione

Alcune configurazioni potrebbero non essere applicabili agli ambienti di database in uso. È ora possibile posticipare di 30 giorni una particolare analisi della configurazione o chiudere l'analisi.



==== Rimozione dei record di valutazione in loco

Dopo aver esaminato i risparmi per un host on-premise di Microsoft SQL Server, è possibile rimuovere il record dell'host on-premise dalla fabbrica dei workload BlueXP .



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Workload VMware



==== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa release della fabbrica di workload BlueXP  per VMware presenta i seguenti miglioramenti per l'esperienza con il Migration ADVISOR di Amazon EC2:

*Informazioni sull'infrastruttura dati NetApp come origine dati*: Workload Factory si connette direttamente con NetApp Data Infrastructure Insights per raccogliere informazioni sulla distribuzione VMware quando si utilizza il data collector del Migration ADVISOR EC2.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Carichi di lavoro Genai



==== Supporto per NetApp Connector per Amazon Q Business

Questa versione di GenAI introduce il supporto per NetApp Connector per Amazon Q Business, consentendo di creare connettori per Amazon Q Business. Sfrutta in modo rapido e semplice l'assistente ai aziendale Amazon Q con una configurazione iniziale inferiore rispetto alla creazione di una knowledge base Genai per Amazon Bedrock.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Crea un connettore NetApp per Amazon Q Business"]



==== Supporto di modelli di chat avanzati

GenAI supporta ora i seguenti modelli di chat aggiuntivi per le knowledge base:

* link:https://docs.mistral.ai/getting-started/models/models_overview/["Modelli Mistral ai"^]
* link:https://docs.aws.amazon.com/bedrock/latest/userguide/titan-text-models.html["Modelli di testo Amazon Titan"^]
* link:https://www.llama.com/docs/model-cards-and-prompt-formats/["Modelli meta Llama"^]
* link:https://docs.ai21.com/["Modelli Jamba 1,5"^]
* link:https://docs.cohere.com/docs/the-cohere-platform["Modelli Cohere Command"^]
* link:https://aws.amazon.com/bedrock/deepseek/["Modelli Deepseek"^]


GenAI supporta i modelli di ciascun provider supportati da Amazon Bedrock: link:https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html["Modelli di base supportati in Amazon Bedrock"^]

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente e la documentazione della Workload Factory ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura/scrittura" per fare riferimento alle autorizzazioni di automazione.



=== Installazione e amministrazione



==== Supporto di completamento automatico di CloudShell

Quando si utilizza la fabbrica CloudShell del carico di lavoro di BlueXP , è possibile iniziare a digitare un comando e premere il tasto Tab per visualizzare le opzioni disponibili. Se esistono più possibilità, l'interfaccia CLI visualizza un elenco di suggerimenti. Questa funzionalità migliora la produttività riducendo al minimo gli errori e accelerando l'esecuzione dei comandi.



==== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente di fabbrica del carico di lavoro e la documentazione ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura-scrittura" per fare riferimento all'automazione delle autorizzazioni.



== 2025-04-04



=== Workload dei database



==== Miglioramenti all'ottimizzazione

Per ottimizzare gli ambienti di database sono disponibili nuove valutazioni di ottimizzazione, correzioni e visualizzazione di più risorse.



===== Valutazioni della resilienza

I miglioramenti includono nuove valutazioni della resilienza per controllare che le funzionalità di ridondanza dei dati e disaster recovery siano configurate per i vostri ambienti di database.

* Backup di FSX per ONTAP: Analizza se i file system FSX per ONTAP che servono i volumi dell'istanza di SQL Server sono configurati con FSX per ONTAP pianificato.
* Replica tra aree: Valuta se FSX per i file system ONTAP che servono le istanze di Microsoft SQL Server è configurato con la replica tra aree.




===== Correzione del calcolo

La correzione RSS (Receive Side Scaling) configura RSS per distribuire l'elaborazione di rete tra più processori e assicurare una distribuzione efficiente del carico.



===== Correzione locale delle snapshot

La correzione locale delle snapshot imposta le policy di snapshot per i volumi per le istanze di Microsoft SQL Server per mantenere resilienti gli ambienti di database in caso di perdita di dati.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



===== Supporto per la selezione di più risorse

Quando si ottimizzano le configurazioni dei database, sarà ora possibile selezionare risorse specifiche invece di tutte le risorse.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



==== Vista inventario migliorata

La scheda inventario nella console workload factory è stata semplificata in modo da contenere solo server SQL in esecuzione su Amazon FSX per NetApp ONTAP. Ora troverai SQL Server on-premise ed in esecuzione su Amazon Elastic Block Store e Amazon FSX per Windows file Server nella scheda Esplora risparmi.



==== Creazione rapida disponibile per la distribuzione di PostgreSQL Server

È possibile utilizzare questa opzione di distribuzione rapida per creare un server PostgreSQL con configurazione ha e procedure consigliate incorporate.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Creare un server PostgreSQL in fabbrica carichi di lavoro BlueXP"]



== 2025-03-30



=== Amazon FSX per NetApp ONTAP



==== Gestione automatica della capacità per sistemi scale-out

Workload Factory ora ricerca gli inode disponibili nei volumi e ne aumenta il conteggio in base alle soglie di gestione automatica della capacità configurate. Questa funzionalità supporta la gestione automatica della capacità per sistemi scale-out. È possibile abilitare la gestione inodes come parte della gestione automatica della capacità.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Consentire la gestione automatica della capacità"]



==== API di ribilanciamento FlexGroup

BlueXP  workload Factory rilascia l'API di ribilanciamento di FlexGroup che ti consente di eseguire un piano per ribilanciare i dati in un FlexGroup. Il ribilanciamento ridistribuisce i dati in modo uniforme nei volumi degli elementi.

link:https://console.workloads.netapp.com/api-doc["Documentazione dell'API di fabbrica del carico di lavoro BlueXP"]



==== Il modulo di replica dei dati include i casi d'utilizzo

Il modulo di replica dei dati include ora casi d'utilizzo che semplificano la compilazione del modulo. Per la replica dei dati, seleziona uno dei seguenti casi d'utilizzo: Migrazione, disaster recovery hot, disaster recovery cold, archivio o altro. Dopo aver selezionato un caso di utilizzo, workload Factory consiglia i valori conformemente alle Best practice. È possibile accettare i valori preselezionati o personalizzare i valori nel modulo.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Replicare i dati"]



==== Modifiche alla terminologia delle policy relative al tiering dei dati

Ora, quando selezioni una policy di tiering durante la creazione di volumi, la replica dei dati o gli aggiornamenti delle policy di tiering esistenti, troverai nuovi termini per descrivere le policy di tiering.

* _Bilanciato (automatico)_
* _Costi ottimizzati (tutti)_
* _Prestazioni ottimizzate (solo Snapshot)_




==== Dettagli del gruppo di protezione per la creazione del file system

Viene creato un gruppo di sicurezza come parte del processo di creazione del file system FSX per ONTAP. Sono ora disponibili i dettagli dei gruppi di sicurezza, inclusi protocolli, porte e ruoli.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Creare un file system"]



=== Workload VMware



==== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa release della fabbrica di workload BlueXP  per VMware presenta diversi miglioramenti all'esperienza del Migration Advisor di Amazon EC2:

* *Guida avanzata all'assegnazione dei volumi*: Le informazioni sull'assegnazione dei volumi nei passaggi "Classify" e "Package" del Migration ADVISOR EC2 offrono una leggibilità e una fruibilità migliorate. Vengono visualizzate informazioni più utili su ciascun volume, che consentono di identificare meglio i volumi e di determinarne l'assegnazione.
* *Miglioramenti all'efficienza degli script di raccolta dati*: Lo script di raccolta dati del Migration ADVISOR EC2 ottimizza l'utilizzo della CPU durante la raccolta dei dati per implementazioni VM di dimensioni inferiori.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]



=== Carichi di lavoro Genai



==== Supporto avanzato dei tipi di file

Questa versione di GenAI introduce il supporto dei formati di file JSON e JSONP durante l'acquisizione di file `.json` da origini dati. Sono supportati i file JSON con oggetti nidificati, con supporto limitato per gli array nidificati.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/identify-data-sources-knowledge-base.html#supported-data-source-file-formats["Formati di file origine dati supportati"]



==== Supporto dell'internazionalizzazione per l'applicazione di esempio chatbot esterna

Ora potete cambiare facilmente l'interfaccia utente dell'applicazione chatbot esterna di esempio GenAI in una lingua o in una lingua diversa.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/AI/GenAI-ChatBot-application-sample#netapp-workload-factory-genai-sample-application["Applicazione chatbot di esempio GenAI esterna"]



==== Supporto per il modello di chat antropico Claude Sonnet 3,7

GenAI ora include il supporto per il modello di chat antropico Claude 3,7 Sonnet. Le funzionalità beta di Claude 3,7 Sonnet consentono fino a 128K token di output per richiesta e supportano nuove azioni di utilizzo del computer. Claude 3,7 Sonnet Extended Thinking Mode sarà supportato in una futura versione di GenAI.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



==== Supporto per l'aggiunta di origini dati da condivisioni NFS/SMB generiche

Utilizzando l'API della farm dei workload, ora puoi aggiungere un'origine dati da una condivisione generica NFSv3, NFSv4 o SMB. Quando Aggiungi un'origine dati da una condivisione NFS o SMB, il volume della Knowledge base rimane su un volume Amazon FSX per NetApp ONTAP. L'interfaccia utente Web di workload Factory supporterà questa funzione in una versione futura.

link:https://console.workloads.netapp.com/api-doc["Utilizza l'API della fabbrica del carico di lavoro"^]



==== Supporto peering VPC

Ora puoi implementare un'infrastruttura Genai link:https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html["Cloud privati virtuali (VPC) in peering"^]nella stessa area e utilizzare il medesimo account AWS. Puoi implementare il motore ai in un VPC e quindi creare una knowledge base in un VPC con peered e selezionare i file system Amazon FSX per NetApp ONTAP che risiedono in un VPC con peered.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



=== Installazione e amministrazione



==== CloudShell riporta risposte di errore generate dall'ai per i comandi CLI di ONTAP

Quando si utilizza CloudShell, ogni volta che si invia un comando CLI di ONTAP e si verifica un errore, è possibile ottenere risposte agli errori generate dall'intelligenza artificiale che includono una descrizione del guasto, la causa del guasto e una risoluzione dettagliata.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilizzare CloudShell"]



==== iam:aggiornamento autorizzazioni SimulatePermissionPolicy

Ora puoi gestire `iam:SimulatePrincipalPolicy` il permesso dalla console workload Factory quando Aggiungi ulteriori credenziali di account AWS o Aggiungi una nuova funzionalità del workload come il workload Genai.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]



== 2025-03-02



=== Workload VMware



==== Miglioramenti al Migration ADVISOR di Amazon EC2

Questa release della fabbrica di workload BlueXP  per VMware presenta diversi miglioramenti all'esperienza del Migration Advisor di Amazon EC2:

* *Tipo di istanza stimato*: Il Migration ADVISOR può ora esaminare i requisiti dell'ambiente e fornire un tipo di istanza Amazon EC2 stimato per ogni VM. Puoi scegliere di includere il tipo di istanza stimata per ogni macchina virtuale durante la fase di ambito del Migration Advisor.
* *Capacità di consigliare i volumi Amazon EBS*: Il Migration ADVISOR può ora consigliare la migrazione dei volumi di dati ad Amazon Elastic Block Store (EBS) invece di Amazon FSX per NetApp ONTAP a causa di specifiche esigenze di capacità o performance di una determinata regione.
* *Assegnazione automatica avanzata del filesystem*: L'assegnazione del filesystem Amazon FSX for NetApp ONTAP è stata migliorata per ottimizzare meglio i costi e ridurre al minimo la velocità di trasmissione.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crea un piano di implementazione per Amazon EC2 utilizzando il Migration Advisor"]



== 2 febbraio 2025



=== Installazione e amministrazione



==== CloudShell disponibile nella console di fabbrica del workload BlueXP

CloudShell è disponibile da qualsiasi luogo nella console della workload Factory di BlueXP . CloudShell ti consente di utilizzare le credenziali AWS e ONTAP fornite nel tuo account BlueXP  ed eseguire i comandi dell'interfaccia a riga di comando di AWS o i comandi dell'interfaccia a riga di comando di ONTAP in un ambiente simile alla shell.

link:https://docs.netapp.com/us-en/workload-setup-admin/use-cloudshell.html["Utilizzare CloudShell"]



==== Aggiornamento delle autorizzazioni per i database

Il seguente permesso è ora disponibile in modalità _Read_ per i database: `iam:SimulatePrincipalPolicy`.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#change-log["Registro delle modifiche di riferimento delle autorizzazioni"]
