= L'ottimizzazione continua aggiunge correzioni e valutazioni di calcolo
:allow-uri-read: 




=== L'ottimizzazione continua aggiunge correzioni e valutazioni di calcolo

I database ora offrono informazioni e consigli per aiutarti a ottimizzare le risorse di calcolo per le istanze di Microsoft SQL Server. Misuriamo l'utilizzo della CPU e sfruttiamo il servizio AWS Compute Optimizer per consigliare tipi di istanze ottimali e dimensionate in modo adeguato e notificare le patch del sistema operativo disponibili. L'ottimizzazione delle risorse di calcolo può aiutarti a prendere decisioni informate sui tipi di istanze, risparmiando sui costi e utilizzando in modo efficiente le risorse.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizzare le configurazioni delle risorse di calcolo"]



=== Supporto PostgreSQL

È ora possibile distribuire e gestire le distribuzioni standalone di PostgreSQL Server nei database.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Creare un server PostgreSQL"]
