= Ottimizza costantemente i tuoi workload Microsoft SQL Server con i database
:allow-uri-read: 




=== Ottimizza costantemente i tuoi workload Microsoft SQL Server con i database

La fabbrica dei carichi di lavoro di BlueXP  introduce linee guida e barriere per garantire l'ottimizzazione costante e il rispetto delle Best practice per la componente di storage dei workload Microsoft SQL Server in Amazon FSX per NetApp ONTAP. Questa funzionalità esegue una scansione continua del tuo ambiente Microsoft SQL Server offline, fornendo un report completo su informazioni, opportunità e consigli per aiutarti a ottenere elevati livelli di performance, convenienza e conformità.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza i workload SQL Server"]



=== Supporto terraforme

È ora possibile utilizzare Terraform dal Codebox per distribuire Microsoft SQL Server.

* link:https://docs.netapp.com/us-en/workload-databases/create-database-server.html["Creare un server di database"^]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"^]

