= Miglioramenti all'ottimizzazione
:allow-uri-read: 




=== Miglioramenti all'ottimizzazione

Per ottimizzare gli ambienti di database sono disponibili nuove valutazioni di ottimizzazione, correzioni e visualizzazione di più risorse.



==== Valutazioni della resilienza

I miglioramenti includono nuove valutazioni della resilienza per controllare che le funzionalità di ridondanza dei dati e disaster recovery siano configurate per i vostri ambienti di database.

* Backup di FSX per ONTAP: Analizza se i file system FSX per ONTAP che servono i volumi dell'istanza di SQL Server sono configurati con FSX per ONTAP pianificato.
* Replica tra aree: Valuta se FSX per i file system ONTAP che servono le istanze di Microsoft SQL Server è configurato con la replica tra aree.




==== Correzione del calcolo

La correzione RSS (Receive Side Scaling) configura RSS per distribuire l'elaborazione di rete tra più processori e assicurare una distribuzione efficiente del carico.



==== Correzione locale delle snapshot

La correzione locale delle snapshot imposta le policy di snapshot per i volumi per le istanze di Microsoft SQL Server per mantenere resilienti gli ambienti di database in caso di perdita di dati.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



==== Supporto per la selezione di più risorse

Quando si ottimizzano le configurazioni dei database, sarà ora possibile selezionare risorse specifiche invece di tutte le risorse.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



=== Vista inventario migliorata

La scheda inventario nella console workload factory è stata semplificata in modo da contenere solo server SQL in esecuzione su Amazon FSX per NetApp ONTAP. Ora troverai SQL Server on-premise ed in esecuzione su Amazon Elastic Block Store e Amazon FSX per Windows file Server nella scheda Esplora risparmi.



=== Creazione rapida disponibile per la distribuzione di PostgreSQL Server

È possibile utilizzare questa opzione di distribuzione rapida per creare un server PostgreSQL con configurazione ha e procedure consigliate incorporate.

link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Creare un server PostgreSQL in fabbrica carichi di lavoro BlueXP"]
