= La BlueXP workload factory ora è NetApp Workload Factory
:allow-uri-read: 




=== La BlueXP workload factory ora è NetApp Workload Factory

BlueXP è stato rinominato e riprogettato per riflettere meglio il ruolo che svolge nella gestione dell'infrastruttura dati. Di conseguenza, BlueXP workload factory è stato rinominato NetApp Workload Factory.



=== Supporto per l'aggiunta di origini dati NFS/SMB generiche nei connettori NetApp per Amazon Q Business

Utilizzando l'API Workload Factory, ora puoi aggiungere un'origine dati da una condivisione NFSv3, NFSv4 o SMB generica a un connettore NetApp per Amazon Q Business. Ciò consente di includere file archiviati su volumi ospitati da file system diversi da Amazon FSx for NetApp ONTAP.

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html["Creare un connettore NetApp per Amazon Q Business"]

link:https://docs.netapp.com/us-en/workload-genai/connector/define-connector.html#add-data-sources-to-the-connector["6320af7d92cd5d357460c5cbc5f642a9"]



=== Configurazione avanzata della chat per le basi di conoscenza

Ora puoi configurare impostazioni di chat avanzate applicabili al modello di chat per la knowledge base, come la lunghezza della risposta, la temperatura, le impostazioni di ragionamento e altro ancora. Alcune di queste impostazioni, come quelle relative alla data di recenza e all'ora di modifica, le impostazioni di recupero avanzate e il prompt di sistema, sono disponibili solo tramite l'API Workload Factory.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]



=== Selezione del tipo di inferenza ora supportata per modelli di incorporamento, chat e riclassificazione

Se il modello di incorporamento, chat o riclassificazione scelto dispone di impostazioni di inferenza, ora è possibile selezionare un tipo di inferenza. Ciò ti consente di adattare meglio le prestazioni del chatbot e i requisiti delle risorse alle tue esigenze.

link:https://docs.netapp.com/us-en/workload-genai/knowledge-base/create-knowledgebase.html["Creare una knowledge base GenAI"]
