= Rilevamento di PostgreSQL e Oracle
:allow-uri-read: 




=== Rilevamento di PostgreSQL e Oracle

Ora puoi individuare le istanze che eseguono database PostgreSQL e distribuzioni di database Oracle nel tuo account AWS all'interno della console di Workload Factory. Le istanze individuate appariranno nell'inventario dei database.



=== Aggiornata la terminologia "Ottimizzazione"

Precedentemente chiamata "Ottimizzazione", la Workload Factory ora utilizza "problemi ben progettati" e "stato ben progettato" per descrivere l'analisi delle configurazioni del database e "correzione" per descrivere la soluzione per le opportunità di migliorare le configurazioni del database al fine di soddisfare le raccomandazioni delle best practice.

link:https://docs.netapp.com/us-en/workload-databases/optimize-overview.html["Analisi della configurazione per ambienti di database nella fabbrica dei carichi di lavoro"]



=== Miglioramento dell'onboarding per le istanze host

Invece di utilizzare i termini "non rilevato", "non gestito" o "gestito" per la gestione delle istanze host, Workload Factory ora utilizza "registra" per l'onboarding delle istanze host. Il nuovo processo di registrazione include l'autenticazione e la preparazione delle istanze host, in modo da poter creare, monitorare, analizzare e correggere le risorse nelle configurazioni del database all'interno della console di Workload Factory. La fase di preparazione del processo di registrazione indica se le istanze host sono pronte per la gestione.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestione delle istanze"]
