= Miglioramenti al dashboard dei database
:allow-uri-read: 




=== Miglioramenti al dashboard dei database

Un nuovo design del Dashboard include le seguenti immagini e miglioramenti:

* Il grafico della distribuzione dell'host mostra il numero di host Microsoft SQL Server e di host PostgreSQL
* I dettagli di distribuzione delle istanze includono il numero totale di istanze rilevate e il numero di istanze gestite di Microsoft SQL Server e PostgreSQL
* I dettagli di distribuzione dei database includono il numero totale di database e il numero di database Microsoft SQL Server e PostgreSQL gestiti
* Punteggio e stati di ottimizzazione per le istanze gestite e online
* Dettagli di ottimizzazione per categorie di applicazioni, calcolo e storage
* Dettagli di ottimizzazione per configurazioni delle istanze di Microsoft SQL Server come dimensionamento dello storage, layout dello storage, storage ONTAP, calcolo e applicazioni
* Potenziali risparmi per i carichi di lavoro dei database in esecuzione su Amazon Elastic Block Store e FSX per ambienti di storage Windows file Server rispetto ad Amazon FSX per lo storage NetApp ONTAP




=== Nuovo stato "completato con problemi" in monitoraggio lavoro

La funzione di monitoraggio dei lavori per i database fornisce ora il nuovo stato "completato con problemi" in modo da poter conoscere quali lavori secondari presentano problemi e quali sono i problemi.

link:https://docs.netapp.com/us-en/workload-databases/monitor-databases.html["Monitorare i database"]



=== Valutazione e ottimizzazione per le licenze Microsoft SQL Server con overprovisioning

Il calcolatore di risparmio valuta ora se Enterprise Edition è necessario per la distribuzione di Microsoft SQL Server. Se una licenza viene fornita in eccesso, il calcolatore consiglia di eseguire il downgrade. Sarà possibile eseguire automaticamente il downgrade della licenza nei database ottimizzando l'applicazione.

* link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Scopri i risparmi con FSX per ONTAP per i carichi di lavoro del database"^]
* link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza i workload SQL Server"]

