= Gestione del volume della cache
:allow-uri-read: 




=== Gestione del volume della cache

È possibile eseguire le seguenti operazioni di gestione del volume della cache dalla console di Workload Factory:

* Modifica il nome della cache
* Aumentare la capacità di un volume di cache
* Modifica il percorso di montaggio o la politica di esportazione per un volume di cache
* Modificare il metodo o la modalità di memorizzazione nella cache per un volume di cache
* Precompilare un volume di cache
* Elimina un volume di cache


link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html["Gestisci i volumi della cache"]



=== Gestione automatica degli inode disponibile

È possibile abilitare la gestione automatica degli inode senza dover abilitare la gestione automatica della capacità.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html["Abilita la gestione automatica degli inode"]



=== Impostazione di avviso di soglia per l'utilizzo di capacità e inode

Sono disponibili avvisi di soglia sia per la capacità che per l'utilizzo degli inode. È possibile impostare queste soglie quando si abilita la gestione automatica della capacità o degli inode. Per utilizzare questa impostazione, dovrai configurare le notifiche utilizzandolink:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Servizio di notifica NetApp Workload Factory"^] .



=== Riduzione delle dimensioni del volume disponibile

È possibile ridurre le dimensioni dei volumi NFS e SMB/CIFS in NetApp Workload Factory. Questa funzionalità consente una migliore gestione delle risorse di archiviazione, consentendo di ridurre le dimensioni dei volumi che non sono più necessari alla loro capacità attuale.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html["Diminuire la capacità di un volume"]



=== FSx migliorato per lo stato delle risorse ONTAP

Workload Factory ha migliorato lo stato della risorsa "non configurata" per includere una spiegazione del problema effettivo della risorsa.



=== Aggiornamenti di analisi ben progettati

Workload Factory analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Utilizzo del volume quasi completo: controlla se uno qualsiasi dei volumi sta utilizzando l'80% o più della propria capacità di file. Ciò consente di identificare i volumi che potrebbero richiedere capacità aggiuntiva.
* Accesso non autorizzato ai volumi: verifica se un volume iSCSI è accessibile tramite un percorso di montaggio NFS o SMB/CIFS e consente di rimuovere l'accesso non autorizzato al volume per evitare rischi per la sicurezza.




=== Modifiche alle autorizzazioni per Workload Factory per Storage

Workload Factory fornisce maggiore chiarezza sulle autorizzazioni richieste per azioni specifiche e granularità per selezionare solo le autorizzazioni necessarie. Quando aggiungi le credenziali, avrai tre opzioni di autorizzazioni tra cui scegliere, anziché il precedente modello di autorizzazioni che era _sola lettura_ e _lettura/scrittura_. Il nuovo modello di autorizzazioni suddivide le policy di autorizzazione come segue:

* _Visualizzazione, pianificazione e analisi_: visualizza i file system FSx per ONTAP , scopri di più sullo stato del sistema, ottieni un'analisi ben progettata per i tuoi sistemi ed esplora i risparmi.
* _Operazioni e risoluzione_: esegui attività operative come la regolazione della capacità del file system e la risoluzione dei problemi relativi alle configurazioni del file system.
* _Creazione ed eliminazione del file system_: crea ed elimina FSx per i file system ONTAP e le VM di archiviazione.


Quando si aggiungono le credenziali, è possibile selezionare una o più di queste policy di autorizzazione in base al livello di accesso che si desidera fornire a Workload Factory.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Riferimento alle autorizzazioni di Workload Factory"]



=== Supporto per FSx per ONTAP Cyber ​​Vault

È possibile creare un cyber vault utilizzando FSx for ONTAP come origine o destinazione nell'architettura del cyber vault. I caveau informatici forniscono un ambiente sicuro e isolato per l'archiviazione di dati critici, proteggendoli da ransomware e altre minacce informatiche.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-cyber-vault.html["Configurare un cyber vault con FSx per ONTAP"]
