= PostgreSQL configurazione ad alta disponibilità
:allow-uri-read: 




=== PostgreSQL configurazione ad alta disponibilità

È ora possibile distribuire una configurazione ad alta disponibilità (ha) per PostgreSQL Server.

link:https://review.docs.netapp.com/us-en/workload-databases_explore-savings-updates/create-postgresql-server.html["Creare un server PostgreSQL"]



=== Supporto terraform per la creazione di server PostgreSQL

È ora possibile utilizzare Terraform dal Codebox per distribuire PostgreSQL.

* link:https://docs.netapp.com/us-en/workload-databases/create-postgresql-server.html["Creare un server di database PostgreSQL"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Utilizzare Terraform da Codebox"]




=== Valutazione della resilienza per la pianificazione locale delle snapshot

Per i carichi di lavoro del database è disponibile una nuova valutazione della resilienza. Valutiamo se i volumi delle istanze di Microsoft SQL Server dispongono di policy di Snapshot pianificate valide. Le snapshot sono copie dei tuoi dati in un determinato momento e contribuiscono a mantenere resilienti gli ambienti di database in caso di perdita di dati.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



=== Ripristino MAXDOP per i carichi di lavoro del database

BlueXP  workload factory per database supporta ora il ripristino della configurazione del server MAXDOP (Maximum grado di parallelismo). Quando la configurazione di MAXDOP non è ottimale, è possibile consentire a BlueXP  workload Factory di ottimizzare la configurazione.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]



=== Report di analisi sui risparmi delle email

Quando esplori i risparmi offerti dal tuo Amazon Elastic Block Store e da FSX per Windows file Server rispetto a FSX per ONTAP, adesso puoi inviare il report di suggerimento via email a te, ai membri del team e ai clienti.
