= Miglioramenti alla scheda Relazioni di replicazione
:allow-uri-read: 




=== Miglioramenti alla scheda Relazioni di replicazione

Abbiamo aggiunto diverse nuove colonne alla tabella delle relazioni di replicazione per fornirti maggiori informazioni sulle relazioni di replicazione nella scheda *Relazioni di replicazione*. La tabella ora include le seguenti colonne:

* Politica SnapMirror
* File system sorgente
* File system di destinazione
* Stato della relazione
* Ultimo orario di trasferimento




=== Miglioramenti alla protezione autonoma dai ransomware NetApp con intelligenza artificiale (ARP/AI)

Questa versione introduce il termine aggiornato "NetApp Autonomous Ransomware Protection with AI (ARP/AI)" per riflettere meglio l'integrazione dell'intelligenza artificiale nelle nostre funzionalità di protezione dal ransomware.

Inoltre, sono stati apportati i seguenti miglioramenti ad ARP/AI:

* ARP/AI a livello di volume: ora puoi abilitare ARP/AI a livello di volume, consentendoti di proteggere volumi specifici all'interno dei file system FSx for ONTAP .
* Creazione automatica di snapshot: è possibile impostare la policy ARP/AI per eseguire snapshot automatici e definire la frequenza con cui vengono eseguiti per i volumi con ARP/AI abilitato, migliorando la strategia di protezione dei dati.
* Snapshot immutabili: ARP/AI ora supporta snapshot immutabili, che non possono essere eliminati o modificati, fornendo un ulteriore livello di sicurezza contro gli attacchi ransomware.
* Rilevamento: include vari metodi di rilevamento, come l'elevata velocità di trasmissione dei dati entropici a livello di volume, la velocità di creazione dei file, la velocità di rinomina dei file, la velocità di eliminazione dei file e l'analisi comportamentale, nonché estensioni di file mai viste prima che aiutano a rilevare anomalie e potenziali attacchi ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Proteggi i tuoi dati con la protezione autonoma dai ransomware NetApp con intelligenza artificiale (ARP/AI)"]



=== Aggiornamenti di analisi ben progettati

Workload Factory ora analizza i file system FSx for ONTAP per le seguenti configurazioni:

* Affidabilità dei dati di conservazione a lungo termine: verifica se le etichette assegnate al criterio di snapshot del volume di origine sono identiche alle etichette assegnate al criterio di conservazione a lungo termine. Quando le etichette sono identiche, la replica dei dati tra i volumi di origine e di destinazione è affidabile.
* NetApp Autonomous Ransomware Protection con AI (ARP/AI): verifica se ARP/AI è abilitato sui file system. Questa funzionalità ti aiuta a rilevare e ripristinare i dati dagli attacchi ransomware.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Visualizza lo stato ben progettato dei tuoi file system FSx per ONTAP"]



=== Escludere una configurazione dall'analisi ben progettata

Ora è possibile escludere una o più configurazioni dall'analisi ben progettata. Ciò consente di ignorare configurazioni specifiche che al momento non si desidera gestire.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Escludere una configurazione dall'analisi ben progettata"]



=== Supporto Terraform per la creazione di link

Ora puoi utilizzare Terraform da Codebox per creare un collegamento per l'associazione con un file system FSx per ONTAP . Questa funzionalità è destinata agli utenti che creano i collegamenti manualmente.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Connettersi a un file system FSX per ONTAP con un collegamento Lambda"]



=== Nuovo supporto regionale per esplorare i risparmi nello spazio di archiviazione

Le seguenti nuove regioni sono ora supportate per esplorare i risparmi per Amazon Elastic Block Store (EBS), FSx per Windows File Server ed Elastic File Systems (EFS):

* Messico
* Thailandia




=== Miglioramenti alla creazione e gestione delle azioni SMB/CIFS

Ora è possibile creare condivisioni SMB/CIFS che puntano alle directory all'interno di un volume. All'interno del volume potrai vedere quali condivisioni esistono, dove puntano e le autorizzazioni concesse a utenti e gruppi specifici.

Per i volumi di protezione dei dati, il flusso di creazione di una condivisione SMB/CIFS ora include la creazione di un percorso di giunzione al volume per scopi di montaggio.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_grogu-5684-wa-dismiss/manage-cifs-share.html#create-a-cifs-share-for-a-volume["Creare una condivisione CIFS per un volume"]
