= Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP
:allow-uri-read: 




=== Supporto del servizio di notifica di fabbrica del carico di lavoro BlueXP

Il servizio di notifica di BlueXP Workload Factory consente a Workload Factory di inviare notifiche al servizio di avvisi BlueXP o a un argomento Amazon SNS. Le notifiche inviate agli avvisi BlueXP vengono visualizzate nel pannello degli avvisi BlueXP. Quando la Workload Factory pubblica notifiche su un argomento Amazon SNS, i sottoscrittori dell'argomento (ad esempio persone o altre applicazioni) ricevono le notifiche sugli endpoint configurati per l'argomento (ad esempio, tramite e-mail o SMS).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html["Configurare le notifiche di fabbrica del carico di lavoro BlueXP"^]

Workload Factory fornisce le seguenti notifiche per i database:

* Rapporto ben progettato
* Distribuzione host




=== Miglioramento dell'onboarding per la registrazione delle istanze

Workload Factory for Databases ha migliorato il processo di onboarding per la registrazione delle istanze in esecuzione su Amazon FSx for NetApp ONTAP .  Ora è possibile selezionare più istanze in blocco per la registrazione.  Una volta registrata un'istanza, è possibile creare e gestire le risorse del database all'interno della console Workload Factory.

link:https://docs.netapp.com/us-en/workload-databases/manage-instance.html["Gestione delle istanze"]



=== Analisi e correzione per l'impostazione del timeout di Microsoft Multipath I/O

Lo stato ben progettato per le istanze del database ora include l'analisi e la correzione per l'impostazione del timeout di Microsoft Multipath I/O (MPIO).  Impostando il timeout MPIO su 60 secondi si garantisce la connettività e la stabilità dell'archiviazione FSx for ONTAP durante i failover.  Se l'impostazione MPIO non è impostata correttamente, Workload Factory fornirà una soluzione per impostare il valore di timeout MPIO su 60 secondi.

link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Implementare configurazioni di database ben progettate nella fabbrica dei carichi di lavoro"]



=== Miglioramenti alla grafica nell'inventario delle istanze

Dalla schermata dell'inventario delle istanze, vari grafici sull'utilizzo delle risorse, come throughput e IOPS, ora visualizzano i dati degli ultimi 7 giorni, in modo da poter monitorare le prestazioni dei nodi SQL dalla console della fabbrica dei carichi di lavoro in modo più efficiente.  Le metriche delle prestazioni raccolte dai nodi SQL verranno salvate in Amazon CloudWatch e potranno essere utilizzate per Logs Insights o per l'integrazione con altri servizi analitici nel tuo ambiente.

Nelle schede Istanze e Database all'interno dell'inventario, abbiamo migliorato la descrizione e la visualizzazione per la protezione.



=== Supporto per l'autenticazione di Windows nella fabbrica dei carichi di lavoro

Ora Workload Factory supporta l'autenticazione di SQL Server tramite utenti autenticati Windows per registrare istanze e beneficiare delle funzionalità di gestione.

link:https://docs.netapp.com/us-en/workload-databases/register-instance.html["Registra le istanze nella fabbrica del carico di lavoro per i database"]
