= Analisi dei costi e pianificazione della migrazione degli ambienti di database on-premise
:allow-uri-read: 




=== Analisi dei costi e pianificazione della migrazione degli ambienti di database on-premise

La fabbrica di workload BlueXP  per i database rileva, analizza e ti aiuta a pianificare la migrazione del database on-premise in Amazon FSX per NetApp ONTAP. Puoi utilizzare il calcolatore di risparmi per stimare il costo di esecuzione dell'ambiente di database on-premise nel cloud e consultare i consigli per la migrazione dell'ambiente di database on-premise nel cloud.

link:https://docs.netapp.com/us-en/workload-databases/explore-savings.html["Esplora i risparmi per gli ambienti di database on-premise"]



=== Nuove valutazioni di ottimizzazione per i database

Le seguenti valutazioni sono ora disponibili in fabbrica per i carichi di lavoro BlueXP  per i database. Queste valutazioni sono incentrate sul rilevamento e sulla protezione da potenziali vulnerabilità di sicurezza e sul rilevamento e sulla riduzione dei colli di bottiglia delle performance.

* *Configurazione RSS (Receive Side Scaling)*: Verifica se la configurazione RSS è abilitata e se il numero di code è impostato sul valore consigliato. La valutazione fornisce anche consigli per ottimizzare la configurazione RSS.
* *Massimo grado di parallelismo (MAXDOP) configurazione server*: La valutazione verifica se MAXDOP è configurato correttamente e fornisce consigli per ottimizzare le prestazioni.
* *Patch di Microsoft SQL Server*: La valutazione verifica se le patch più recenti sono installate nelle istanze di SQL Server e fornisce consigli per installare le patch più recenti.


link:https://docs.netapp.com/us-en/workload-databases/optimize-configurations.html["Ottimizza le configurazioni"]
