= Miglioramenti alla gestione automatica della capacità
:allow-uri-read: 




=== Miglioramenti alla gestione automatica della capacità

Quando la gestione automatica della capacità è attivata, la fabbrica del carico di lavoro BlueXP  ora controlla se un file system ha raggiunto la propria soglia di capacità ogni 30 minuti invece che ogni 2 ore.

L'impostazione IOPS di provisioning non viene più influenzata dal raggiungimento della soglia di capacità.



=== Snapshot immutabili

Ora è possibile bloccare gli snapshot, rendendoli immutabili, per un periodo di conservazione specifico. Il blocco impedisce l'accesso non autorizzato e l'eliminazione dannosa degli snapshot. È possibile attivare snapshot immutabili durante la creazione di policy di snapshot, durante la creazione di snapshot manuali e dopo la creazione di snapshot.



=== Aggiornamento dei file immutabili

Ora puoi apportare le seguenti modifiche alla configurazione dei file immutabili: Policy di conservazione, periodo di conservazione, periodo di autocommit e modalità di aggiunta del volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-immutable-files.html["Gestire i file immutabili"]



=== Miglioramenti alla replica dei dati

* Replica tra account diversi: La replica tra due account AWS è supportata nella console factory del carico di lavoro BlueXP  nonché nella gestione della replica.
* Pausa e ripresa della replica: È possibile mettere in pausa (disattivare) gli aggiornamenti di replica pianificati dal volume di origine al volume di destinazione e quindi riprendere la pianificazione della replica quando si è pronti. Durante la pausa, i volumi di origine e destinazione diventano indipendenti, mentre il volume di destinazione passa da sola lettura a lettura e scrittura.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/pause-resume-replication.html["Sospendere e riprendere una relazione di replica"]





=== Eventi CloudShell in Tracker

Ora puoi tenere traccia degli eventi CloudShell in Tracker.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Scopri come monitorare e monitorare le operazioni con Tracker"]
