= Protezione autonoma dal ransomware per file system FSX per ONTAP
:allow-uri-read: 




=== Protezione autonoma dal ransomware per file system FSX per ONTAP

Proteggi i tuoi dati con la protezione autonoma dal ransomware (ARP), una funzionalità che sfrutta l'analisi dei workload negli ambienti NAS (NFS/SMB) per rilevare e informare l'utente in caso di attività anomale che potrebbero essere un attacco ransomware. Quando si sospetta un attacco, ARP crea anche nuove istantanee immutabili da cui è possibile ripristinare i dati.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/ransomware-protection.html["Proteggi i tuoi dati con la protezione autonoma dal ransomware"]



=== Potenziamento del ribilanciamento dei volumi di FlexGroup

BlueXP  workload Factory introduce la procedura guidata per il ribilanciamento dei volumi FlexGroup con diverse opzioni di layout per il ribilanciamento dei dati in un volume FlexGroup. Il ribilanciamento ridistribuisce i dati in modo uniforme nei volumi dei membri FlexGroup.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html["Ribilanciare la capacità in un volume FlexGroup"]



=== Implementare le Best practice per un file system FSX per ONTAP

La fabbrica dei carichi di lavoro di BlueXP  fornisce una dashboard in cui puoi esaminare lo stato con l'architettura ideale delle configurazioni del file system. Puoi sfruttare questa analisi per implementare le Best practice per i file system FSX per ONTAP. L'analisi della configurazione del file system include le seguenti configurazioni: Soglia di capacità SSD, snapshot locali pianificate, backup FSX for ONTAP pianificati, tiering dei dati e replica dei dati remota.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/configuration-analysis.html["Scopri l'analisi con un'architettura ideale per le configurazioni del file system"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html["Implementare le Best practice per i file system"]




=== Opzioni per lo stile di sicurezza del volume a doppio protocollo

È possibile scegliere NTFS o UNIX come stile di protezione per un volume per determinare il metodo a cui gli utenti e le autorizzazioni accedono a un volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html["Creare un volume"]



=== Miglioramenti alla replica



==== Replica inversa supportata da FSX per ONTAP a on-premise

La replica inversa è ora disponibile da un file system FSX per ONTAP a un cluster ONTAP on-premise dall'interno della console della workload factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/reverse-replication.html["Replica inversa"]



==== Replica di un volume di data Protection

Ora puoi replicare i volumi di data Protection.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/cascade-replication.html["Replica di un volume di data Protection"]



==== Selezione di più volumi

È disponibile la selezione di più volumi, in modo da poter selezionare esattamente i volumi da replicare.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Creare una relazione di replica"]



==== Etichette di criteri di conservazione a lungo termine

Quando si attiva la conservazione a lungo termine per una relazione di replica, le etichette dei volumi di origine e di destinazione devono corrispondere esattamente. Ora BlueXP  workload Factory può creare automaticamente etichette del volume di origine mancanti.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html["Creare una relazione di replica"]



=== Il nome del file FSX per ONTAP è visibile nella creazione del volume

Abbiamo migliorato la visibilità dei file system FSX per ONTAP durante la creazione dei volumi. Quando crei un volume, visualizzerai il file system FSX per ONTAP, in modo da sapere esattamente dove viene creato il volume.



=== Account AWS visibile per tutto il workload dello storage

Abbiamo migliorato la visibilità degli account sul workload dello storage. L'account AWS viene visualizzato quando si accede alle schede *volumi*, *Storage VM* e *Replication*.



=== Miglioramenti dell'associazione di collegamento

* È possibile associare rapidamente un collegamento da un file system FSX per ONTAP nella scheda inventario.
* BlueXP  workload Factory ora supporta l'utilizzo di credenziali utente ONTAP alternative per l'associazione dei collegamenti.




=== Supporto di autenticazione link per AWS Secrets Manager

Ora hai la possibilità di utilizzare i segreti di AWS Secrets Manager per autenticare i link in modo da non dover utilizzare le credenziali memorizzate nella fabbrica dei workload BlueXP .



=== Supporto risposta Tracker

Tracker ora fornisce le risposte API in modo da poter vedere l'output dell'API REST relativo all'attività.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/monitor-operations.html["Monitoraggio delle operazioni con Tracker"]



=== Convalida della capacità durante il ripristino di un volume da un backup

Quando si ripristina un volume da un backup, la fabbrica del carico di lavoro BlueXP  determina se si dispone di capacità sufficiente per il ripristino e, in caso contrario, può aggiungere automaticamente capacità del livello di storage SSD.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-from-backup.html["Ripristinare un volume da un backup"]



=== Supporto per credenziali utente ONTAP alternative

Workload Factory ora supporta set alternativi di credenziali ONTAP per la creazione di file system al fine di ridurre al minimo i rischi per la sicurezza. Invece di utilizzare solo l'utente fsxadmin, è possibile selezionare un diverso set di credenziali ONTAP o scegliere di non fornire una password per gli utenti fsxadmin e vsaadmin.



=== Terminologia aggiornata per le autorizzazioni

L'interfaccia utente di fabbrica del carico di lavoro e la documentazione ora utilizzano "sola lettura" per fare riferimento alle autorizzazioni di lettura e "lettura-scrittura" per fare riferimento all'automazione delle autorizzazioni.
