= Esploratore di volumi
:allow-uri-read: 




[[volumes-explorer]]
=== Esploratore di volumi

Esplora volumi offre una visualizzazione semplice e ricercabile di tutti i tuoi volumi in NetApp Workload Factory. Vedi subito quali volumi gestiscono carichi di lavoro a blocchi o a file. Visualizza la dimensione logica di ogni volume, la capacità fisica utilizzata e se utilizza funzionalità di efficienza dello storage (compressione, deduplicazione e compaction). Filtra e ordina per nome, stato (disponibile/non funzionante), latenza, dimensione, capacità utilizzata e funzionalità di protezione.



[[enhanced-email-notifications-for-replication-delays]]
=== Notifiche e-mail migliorate per i ritardi di replica

Le notifiche e-mail relative ai ritardi di replica ora includono maggiori dettagli sulla relazione interessata. La notifica ti aiuta a identificare rapidamente la relazione interessata e a esaminarla nella console di Workload Factory.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-replication-delays.html["Abilita le notifiche per i ritardi di replica"]



[[block-device-creation-enhancement]]
=== Miglioramento della creazione di dispositivi a blocchi

Workload Factory supporta la creazione di dispositivi a blocchi a partire da uno snapshot di volume.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-block-device.html["Crea un dispositivo a blocchi da uno snapshot di volume in Workload Factory"]



[[workload-tagging-for-volumes-and-block-devices]]
=== Etichettatura dei carichi di lavoro per volumi e dispositivi a blocchi

Workload Factory ora identifica e tagga volumi e dispositivi a blocchi in base al carico di lavoro o all'applicazione principale. Puoi assegnare tag di carico di lavoro predefiniti come Microsoft SQL Server o Oracle Database, oppure creare tag personalizzati per le tue applicazioni. I tag possono essere applicati a singole risorse o ereditati dalle risorse di storage collegate. Questo ti aiuta ad allineare le configurazioni di storage ai requisiti del carico di lavoro, a capire l'impatto degli incidenti e a risolvere i problemi in modo più efficace.
